"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.connectors.api_pb2
import core.protos.playbooks.folders.folder_pb2
import core.protos.playbooks.playbook_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetFoldersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    FOLDER_IDS_FIELD_NUMBER: builtins.int
    FOLDER_NAME_FIELD_NUMBER: builtins.int
    HIGH_LEVEL_ONLY_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def folder_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.wrappers_pb2.UInt64Value]: ...
    @property
    def folder_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def high_level_only(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        folder_ids: collections.abc.Iterable[google.protobuf.wrappers_pb2.UInt64Value] | None = ...,
        folder_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        high_level_only: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder_name", b"folder_name", "high_level_only", b"high_level_only", "meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder_ids", b"folder_ids", "folder_name", b"folder_name", "high_level_only", b"high_level_only", "meta", b"meta"]) -> None: ...

global___GetFoldersRequest = GetFoldersRequest

@typing.final
class GetFoldersResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    FOLDERS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    @property
    def folders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.playbooks.folders.folder_pb2.Folder]: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
        folders: collections.abc.Iterable[core.protos.playbooks.folders.folder_pb2.Folder] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folders", b"folders", "message", b"message", "meta", b"meta", "success", b"success"]) -> None: ...

global___GetFoldersResponse = GetFoldersResponse

@typing.final
class CreateFolderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    FOLDER_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def folder(self) -> core.protos.playbooks.folders.folder_pb2.Folder: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        folder: core.protos.playbooks.folders.folder_pb2.Folder | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder", b"folder", "meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder", b"folder", "meta", b"meta"]) -> None: ...

global___CreateFolderRequest = CreateFolderRequest

@typing.final
class CreateFolderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    FOLDER_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    @property
    def folder(self) -> core.protos.playbooks.folders.folder_pb2.Folder: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
        folder: core.protos.playbooks.folders.folder_pb2.Folder | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder", b"folder", "message", b"message", "meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder", b"folder", "message", b"message", "meta", b"meta", "success", b"success"]) -> None: ...

global___CreateFolderResponse = CreateFolderResponse

@typing.final
class UpdateFolderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    FOLDER_ID_FIELD_NUMBER: builtins.int
    UPDATE_FOLDER_OPS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def folder_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def update_folder_ops(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.playbooks.folders.folder_pb2.UpdateFolderOp]: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        folder_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        update_folder_ops: collections.abc.Iterable[core.protos.playbooks.folders.folder_pb2.UpdateFolderOp] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder_id", b"folder_id", "meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder_id", b"folder_id", "meta", b"meta", "update_folder_ops", b"update_folder_ops"]) -> None: ...

global___UpdateFolderRequest = UpdateFolderRequest

@typing.final
class UpdateFolderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    FOLDER_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    @property
    def folder(self) -> core.protos.playbooks.folders.folder_pb2.Folder: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
        folder: core.protos.playbooks.folders.folder_pb2.Folder | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder", b"folder", "message", b"message", "meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder", b"folder", "message", b"message", "meta", b"meta", "success", b"success"]) -> None: ...

global___UpdateFolderResponse = UpdateFolderResponse

@typing.final
class GetFolderPlaybooksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    FOLDER_ID_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def folder_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        folder_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder_id", b"folder_id", "meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder_id", b"folder_id", "meta", b"meta"]) -> None: ...

global___GetFolderPlaybooksRequest = GetFolderPlaybooksRequest

@typing.final
class GetFolderPlaybooksResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PLAYBOOKS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    @property
    def playbooks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.playbooks.playbook_pb2.Playbook]: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
        playbooks: collections.abc.Iterable[core.protos.playbooks.playbook_pb2.Playbook] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "playbooks", b"playbooks", "success", b"success"]) -> None: ...

global___GetFolderPlaybooksResponse = GetFolderPlaybooksResponse

@typing.final
class GetSubfoldersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PARENT_FOLDER_ID_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def parent_folder_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        parent_folder_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta", "parent_folder_id", b"parent_folder_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["meta", b"meta", "parent_folder_id", b"parent_folder_id"]) -> None: ...

global___GetSubfoldersRequest = GetSubfoldersRequest

@typing.final
class GetSubfoldersResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    SUBFOLDERS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    @property
    def subfolders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.playbooks.folders.folder_pb2.Folder]: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
        subfolders: collections.abc.Iterable[core.protos.playbooks.folders.folder_pb2.Folder] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "subfolders", b"subfolders", "success", b"success"]) -> None: ...

global___GetSubfoldersResponse = GetSubfoldersResponse

@typing.final
class MovePlaybookRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOK_ID_FIELD_NUMBER: builtins.int
    NEW_FOLDER_ID_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def playbook_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def new_folder_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        playbook_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        new_folder_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta", "new_folder_id", b"new_folder_id", "playbook_id", b"playbook_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["meta", b"meta", "new_folder_id", b"new_folder_id", "playbook_id", b"playbook_id"]) -> None: ...

global___MovePlaybookRequest = MovePlaybookRequest

@typing.final
class MovePlaybookResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PLAYBOOK_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    @property
    def playbook(self) -> core.protos.playbooks.playbook_pb2.Playbook: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
        playbook: core.protos.playbooks.playbook_pb2.Playbook | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "playbook", b"playbook", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "playbook", b"playbook", "success", b"success"]) -> None: ...

global___MovePlaybookResponse = MovePlaybookResponse
