"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Folder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    PLAYBOOK_COUNT_FIELD_NUMBER: builtins.int
    PARENT_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def created_by(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    created_at: builtins.int
    updated_at: builtins.int
    @property
    def playbook_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def parent_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        created_by: google.protobuf.wrappers_pb2.StringValue | None = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
        playbook_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        parent_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_by", b"created_by", "description", b"description", "id", b"id", "is_active", b"is_active", "name", b"name", "parent_id", b"parent_id", "playbook_count", b"playbook_count"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "created_by", b"created_by", "description", b"description", "id", b"id", "is_active", b"is_active", "name", b"name", "parent_id", b"parent_id", "playbook_count", b"playbook_count", "updated_at", b"updated_at"]) -> None: ...

global___Folder = Folder

@typing_extensions.final
class UpdateFolderOp(google.protobuf.message.Message):
    """CRUD protos"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Op:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OpEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdateFolderOp._Op.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: UpdateFolderOp._Op.ValueType  # 0
        UPDATE_STATUS: UpdateFolderOp._Op.ValueType  # 2
        UPDATE_FOLDER: UpdateFolderOp._Op.ValueType  # 3
        MOVE_LOCATION: UpdateFolderOp._Op.ValueType  # 4

    class Op(_Op, metaclass=_OpEnumTypeWrapper): ...
    UNKNOWN: UpdateFolderOp.Op.ValueType  # 0
    UPDATE_STATUS: UpdateFolderOp.Op.ValueType  # 2
    UPDATE_FOLDER: UpdateFolderOp.Op.ValueType  # 3
    MOVE_LOCATION: UpdateFolderOp.Op.ValueType  # 4

    @typing_extensions.final
    class UpdateFolder(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        FOLDER_FIELD_NUMBER: builtins.int
        @property
        def folder(self) -> global___Folder: ...
        def __init__(
            self,
            *,
            folder: global___Folder | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["folder", b"folder"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["folder", b"folder"]) -> None: ...

    @typing_extensions.final
    class UpdateStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_ACTIVE_FIELD_NUMBER: builtins.int
        DELETE_PLAYBOOKS_FIELD_NUMBER: builtins.int
        @property
        def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        @property
        def delete_playbooks(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
            delete_playbooks: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["delete_playbooks", b"delete_playbooks", "is_active", b"is_active"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["delete_playbooks", b"delete_playbooks", "is_active", b"is_active"]) -> None: ...

    @typing_extensions.final
    class MoveLocation(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PARENT_ID_FIELD_NUMBER: builtins.int
        @property
        def parent_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        def __init__(
            self,
            *,
            parent_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parent_id", b"parent_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["parent_id", b"parent_id"]) -> None: ...

    OP_FIELD_NUMBER: builtins.int
    UPDATE_FOLDER_FIELD_NUMBER: builtins.int
    UPDATE_STATUS_FIELD_NUMBER: builtins.int
    MOVE_LOCATION_FIELD_NUMBER: builtins.int
    op: global___UpdateFolderOp.Op.ValueType
    @property
    def update_folder(self) -> global___UpdateFolderOp.UpdateFolder: ...
    @property
    def update_status(self) -> global___UpdateFolderOp.UpdateStatus: ...
    @property
    def move_location(self) -> global___UpdateFolderOp.MoveLocation: ...
    def __init__(
        self,
        *,
        op: global___UpdateFolderOp.Op.ValueType = ...,
        update_folder: global___UpdateFolderOp.UpdateFolder | None = ...,
        update_status: global___UpdateFolderOp.UpdateStatus | None = ...,
        move_location: global___UpdateFolderOp.MoveLocation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["move_location", b"move_location", "update", b"update", "update_folder", b"update_folder", "update_status", b"update_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["move_location", b"move_location", "op", b"op", "update", b"update", "update_folder", b"update_folder", "update_status", b"update_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["update", b"update"]) -> typing_extensions.Literal["update_folder", "update_status", "move_location"] | None: ...

global___UpdateFolderOp = UpdateFolderOp
