"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConfluenceCloud(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TaskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ConfluenceCloud._TaskType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: ConfluenceCloud._TaskType.ValueType  # 0
        FETCH_DOCUMENT_CONTENT: ConfluenceCloud._TaskType.ValueType  # 1

    class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...
    UNKNOWN: ConfluenceCloud.TaskType.ValueType  # 0
    FETCH_DOCUMENT_CONTENT: ConfluenceCloud.TaskType.ValueType  # 1

    @typing.final
    class FetchDocumentContent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        SPACE_KEY_FIELD_NUMBER: builtins.int
        TITLE_FIELD_NUMBER: builtins.int
        @property
        def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def space_key(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            space_key: google.protobuf.wrappers_pb2.StringValue | None = ...,
            title: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["id", b"id", "space_key", b"space_key", "title", b"title"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["id", b"id", "space_key", b"space_key", "title", b"title"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    FETCH_DOCUMENT_CONTENT_FIELD_NUMBER: builtins.int
    type: Global___ConfluenceCloud.TaskType.ValueType
    @property
    def fetch_document_content(self) -> Global___ConfluenceCloud.FetchDocumentContent: ...
    def __init__(
        self,
        *,
        type: Global___ConfluenceCloud.TaskType.ValueType = ...,
        fetch_document_content: Global___ConfluenceCloud.FetchDocumentContent | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fetch_document_content", b"fetch_document_content", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fetch_document_content", b"fetch_document_content", "task", b"task", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["task", b"task"]) -> typing.Literal["fetch_document_content"] | None: ...

Global___ConfluenceCloud: typing_extensions.TypeAlias = ConfluenceCloud
