"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CustomStrategies(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TaskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CustomStrategies._TaskType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: CustomStrategies._TaskType.ValueType  # 0
        INVESTIGATE_SERVICE_ERROR_RATE_ALERT: CustomStrategies._TaskType.ValueType  # 1
        CHECK_EC2_INSTANCE_HEALTH: CustomStrategies._TaskType.ValueType  # 2
        INVESTIGATE_ERROR_RATE_ALERT_OTEL: CustomStrategies._TaskType.ValueType  # 3
        CHECK_KUBERNETES_POD_HEALTH: CustomStrategies._TaskType.ValueType  # 4
        CHECK_KUBERNETES_NODE_HEALTH: CustomStrategies._TaskType.ValueType  # 5
        CHECK_KUBERNETES_INGRESS_HEALTH: CustomStrategies._TaskType.ValueType  # 6
        INVESTIGATE_REDIS_IN_DATADOG: CustomStrategies._TaskType.ValueType  # 7
        INVESTIGATE_RDS_IN_DATADOG: CustomStrategies._TaskType.ValueType  # 8

    class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...
    UNKNOWN: CustomStrategies.TaskType.ValueType  # 0
    INVESTIGATE_SERVICE_ERROR_RATE_ALERT: CustomStrategies.TaskType.ValueType  # 1
    CHECK_EC2_INSTANCE_HEALTH: CustomStrategies.TaskType.ValueType  # 2
    INVESTIGATE_ERROR_RATE_ALERT_OTEL: CustomStrategies.TaskType.ValueType  # 3
    CHECK_KUBERNETES_POD_HEALTH: CustomStrategies.TaskType.ValueType  # 4
    CHECK_KUBERNETES_NODE_HEALTH: CustomStrategies.TaskType.ValueType  # 5
    CHECK_KUBERNETES_INGRESS_HEALTH: CustomStrategies.TaskType.ValueType  # 6
    INVESTIGATE_REDIS_IN_DATADOG: CustomStrategies.TaskType.ValueType  # 7
    INVESTIGATE_RDS_IN_DATADOG: CustomStrategies.TaskType.ValueType  # 8

    @typing_extensions.final
    class InvestigateServiceErrorRateAlert(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ALERT_ID_FIELD_NUMBER: builtins.int
        @property
        def alert_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            alert_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["alert_id", b"alert_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["alert_id", b"alert_id"]) -> None: ...

    @typing_extensions.final
    class CheckEc2InstanceHealth(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        REGION_FIELD_NUMBER: builtins.int
        INSTANCE_ID_FIELD_NUMBER: builtins.int
        @property
        def region(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def instance_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            region: google.protobuf.wrappers_pb2.StringValue | None = ...,
            instance_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["instance_id", b"instance_id", "region", b"region"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["instance_id", b"instance_id", "region", b"region"]) -> None: ...

    @typing_extensions.final
    class InvestigateServiceErrorRateAlertOtel(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SERVICE_NAME_FIELD_NUMBER: builtins.int
        OP_NAME_FIELD_NUMBER: builtins.int
        ALERT_ID_FIELD_NUMBER: builtins.int
        @property
        def service_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def op_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def alert_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            service_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            op_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            alert_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["alert_id", b"alert_id", "op_name", b"op_name", "service_name", b"service_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["alert_id", b"alert_id", "op_name", b"op_name", "service_name", b"service_name"]) -> None: ...

    @typing_extensions.final
    class CheckKubernetesPodHealth(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        POD_NAME_FIELD_NUMBER: builtins.int
        NAMESPACE_FIELD_NUMBER: builtins.int
        CLUSTER_FIELD_NUMBER: builtins.int
        @property
        def pod_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def namespace(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def cluster(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            pod_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            namespace: google.protobuf.wrappers_pb2.StringValue | None = ...,
            cluster: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "namespace", b"namespace", "pod_name", b"pod_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "namespace", b"namespace", "pod_name", b"pod_name"]) -> None: ...

    @typing_extensions.final
    class CheckKubernetesNodeHealth(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NODE_NAME_FIELD_NUMBER: builtins.int
        CLUSTER_FIELD_NUMBER: builtins.int
        @property
        def node_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def cluster(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            node_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            cluster: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "node_name", b"node_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "node_name", b"node_name"]) -> None: ...

    @typing_extensions.final
    class CheckKubernetesIngressHealth(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INGRESS_NAME_FIELD_NUMBER: builtins.int
        NAMESPACE_FIELD_NUMBER: builtins.int
        CLUSTER_FIELD_NUMBER: builtins.int
        @property
        def ingress_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def namespace(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def cluster(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            ingress_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            namespace: google.protobuf.wrappers_pb2.StringValue | None = ...,
            cluster: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "ingress_name", b"ingress_name", "namespace", b"namespace"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "ingress_name", b"ingress_name", "namespace", b"namespace"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    INVESTIGATE_SERVICE_ERROR_RATE_ALERT_FIELD_NUMBER: builtins.int
    CHECK_EC2_INSTANCE_HEALTH_FIELD_NUMBER: builtins.int
    INVESTIGATE_SERVICE_ERROR_RATE_ALERT_OTEL_FIELD_NUMBER: builtins.int
    CHECK_KUBERNETES_POD_HEALTH_FIELD_NUMBER: builtins.int
    CHECK_KUBERNETES_NODE_HEALTH_FIELD_NUMBER: builtins.int
    CHECK_KUBERNETES_INGRESS_HEALTH_FIELD_NUMBER: builtins.int
    INVESTIGATE_REDIS_IN_DATADOG_FIELD_NUMBER: builtins.int
    INVESTIGATE_RDS_IN_DATADOG_FIELD_NUMBER: builtins.int
    type: global___CustomStrategies.TaskType.ValueType
    @property
    def investigate_service_error_rate_alert(self) -> global___CustomStrategies.InvestigateServiceErrorRateAlert: ...
    @property
    def check_ec2_instance_health(self) -> global___CustomStrategies.CheckEc2InstanceHealth: ...
    @property
    def investigate_service_error_rate_alert_otel(self) -> global___CustomStrategies.InvestigateServiceErrorRateAlertOtel: ...
    @property
    def check_kubernetes_pod_health(self) -> global___CustomStrategies.CheckKubernetesPodHealth: ...
    @property
    def check_kubernetes_node_health(self) -> global___CustomStrategies.CheckKubernetesNodeHealth: ...
    @property
    def check_kubernetes_ingress_health(self) -> global___CustomStrategies.CheckKubernetesIngressHealth: ...
    @property
    def investigate_redis_in_datadog(self) -> global___CustomStrategies.InvestigateServiceErrorRateAlert: ...
    @property
    def investigate_rds_in_datadog(self) -> global___CustomStrategies.InvestigateServiceErrorRateAlert: ...
    def __init__(
        self,
        *,
        type: global___CustomStrategies.TaskType.ValueType = ...,
        investigate_service_error_rate_alert: global___CustomStrategies.InvestigateServiceErrorRateAlert | None = ...,
        check_ec2_instance_health: global___CustomStrategies.CheckEc2InstanceHealth | None = ...,
        investigate_service_error_rate_alert_otel: global___CustomStrategies.InvestigateServiceErrorRateAlertOtel | None = ...,
        check_kubernetes_pod_health: global___CustomStrategies.CheckKubernetesPodHealth | None = ...,
        check_kubernetes_node_health: global___CustomStrategies.CheckKubernetesNodeHealth | None = ...,
        check_kubernetes_ingress_health: global___CustomStrategies.CheckKubernetesIngressHealth | None = ...,
        investigate_redis_in_datadog: global___CustomStrategies.InvestigateServiceErrorRateAlert | None = ...,
        investigate_rds_in_datadog: global___CustomStrategies.InvestigateServiceErrorRateAlert | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["check_ec2_instance_health", b"check_ec2_instance_health", "check_kubernetes_ingress_health", b"check_kubernetes_ingress_health", "check_kubernetes_node_health", b"check_kubernetes_node_health", "check_kubernetes_pod_health", b"check_kubernetes_pod_health", "investigate_rds_in_datadog", b"investigate_rds_in_datadog", "investigate_redis_in_datadog", b"investigate_redis_in_datadog", "investigate_service_error_rate_alert", b"investigate_service_error_rate_alert", "investigate_service_error_rate_alert_otel", b"investigate_service_error_rate_alert_otel", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["check_ec2_instance_health", b"check_ec2_instance_health", "check_kubernetes_ingress_health", b"check_kubernetes_ingress_health", "check_kubernetes_node_health", b"check_kubernetes_node_health", "check_kubernetes_pod_health", b"check_kubernetes_pod_health", "investigate_rds_in_datadog", b"investigate_rds_in_datadog", "investigate_redis_in_datadog", b"investigate_redis_in_datadog", "investigate_service_error_rate_alert", b"investigate_service_error_rate_alert", "investigate_service_error_rate_alert_otel", b"investigate_service_error_rate_alert_otel", "task", b"task", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task", b"task"]) -> typing_extensions.Literal["investigate_service_error_rate_alert", "check_ec2_instance_health", "investigate_service_error_rate_alert_otel", "check_kubernetes_pod_health", "check_kubernetes_node_health", "check_kubernetes_ingress_health", "investigate_redis_in_datadog", "investigate_rds_in_datadog"] | None: ...

global___CustomStrategies = CustomStrategies
