# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/drd_proxy_agent_task.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCprotos/playbooks/source_task_definitions/drd_proxy_agent_task.proto\x12\x15\x63ore.protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\"\xf5\x01\n\rDrdProxyAgent\x12;\n\x04type\x18\x01 \x01(\x0e\x32-.core.protos.playbooks.DrdProxyAgent.TaskType\x12?\n\x07\x63ommand\x18\x02 \x01(\x0b\x32,.core.protos.playbooks.DrdProxyAgent.CommandH\x00\x1a\x38\n\x07\x43ommand\x12-\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"$\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43OMMAND\x10\x01\x42\x06\n\x04taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.drd_proxy_agent_task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DRDPROXYAGENT']._serialized_start=127
  _globals['_DRDPROXYAGENT']._serialized_end=372
  _globals['_DRDPROXYAGENT_COMMAND']._serialized_start=270
  _globals['_DRDPROXYAGENT_COMMAND']._serialized_end=326
  _globals['_DRDPROXYAGENT_TASKTYPE']._serialized_start=328
  _globals['_DRDPROXYAGENT_TASKTYPE']._serialized_end=364
# @@protoc_insertion_point(module_scope)
