# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/protos/playbooks/source_task_definitions/kubectl_task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'core/protos/playbooks/source_task_definitions/kubectl_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@core/protos/playbooks/source_task_definitions/kubectl_task.proto\x12\x15\x63ore.protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\"\x83\x03\n\x07Kubectl\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.core.protos.playbooks.Kubectl.TaskType\x12\x39\n\x07\x63ommand\x18\x02 \x01(\x0b\x32&.core.protos.playbooks.Kubectl.CommandH\x00\x12H\n\x11k8s_write_command\x18\x03 \x01(\x0b\x32+.core.protos.playbooks.Kubectl.WriteCommandH\x00\x1a\x38\n\x07\x43ommand\x12-\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x1a=\n\x0cWriteCommand\x12-\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\";\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43OMMAND\x10\x01\x12\x15\n\x11K8S_WRITE_COMMAND\x10\x02\x42\x06\n\x04taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.playbooks.source_task_definitions.kubectl_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KUBECTL']._serialized_start=124
  _globals['_KUBECTL']._serialized_end=511
  _globals['_KUBECTL_COMMAND']._serialized_start=323
  _globals['_KUBECTL_COMMAND']._serialized_end=379
  _globals['_KUBECTL_WRITECOMMAND']._serialized_start=381
  _globals['_KUBECTL_WRITECOMMAND']._serialized_end=442
  _globals['_KUBECTL_TASKTYPE']._serialized_start=444
  _globals['_KUBECTL_TASKTYPE']._serialized_end=503
# @@protoc_insertion_point(module_scope)
