"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Linear(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TaskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Linear._TaskType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Linear._TaskType.ValueType  # 0
        CREATE_ISSUE: Linear._TaskType.ValueType  # 1
        ASSIGN_ISSUE: Linear._TaskType.ValueType  # 2
        GET_USERS: Linear._TaskType.ValueType  # 3
        GET_ISSUE: Linear._TaskType.ValueType  # 4
        SEARCH_ISSUES: Linear._TaskType.ValueType  # 5
        ADD_COMMENT: Linear._TaskType.ValueType  # 6
        GET_TEAMS: Linear._TaskType.ValueType  # 7
        GET_WORKFLOW_STATES: Linear._TaskType.ValueType  # 8

    class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...
    UNKNOWN: Linear.TaskType.ValueType  # 0
    CREATE_ISSUE: Linear.TaskType.ValueType  # 1
    ASSIGN_ISSUE: Linear.TaskType.ValueType  # 2
    GET_USERS: Linear.TaskType.ValueType  # 3
    GET_ISSUE: Linear.TaskType.ValueType  # 4
    SEARCH_ISSUES: Linear.TaskType.ValueType  # 5
    ADD_COMMENT: Linear.TaskType.ValueType  # 6
    GET_TEAMS: Linear.TaskType.ValueType  # 7
    GET_WORKFLOW_STATES: Linear.TaskType.ValueType  # 8

    @typing_extensions.final
    class CreateIssue(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEAM_ID_FIELD_NUMBER: builtins.int
        TITLE_FIELD_NUMBER: builtins.int
        DESCRIPTION_FIELD_NUMBER: builtins.int
        PRIORITY_FIELD_NUMBER: builtins.int
        LABELS_FIELD_NUMBER: builtins.int
        ASSIGNEE_ID_FIELD_NUMBER: builtins.int
        STATE_ID_FIELD_NUMBER: builtins.int
        @property
        def team_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def priority(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def labels(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def assignee_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def state_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            team_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            title: google.protobuf.wrappers_pb2.StringValue | None = ...,
            description: google.protobuf.wrappers_pb2.StringValue | None = ...,
            priority: google.protobuf.wrappers_pb2.StringValue | None = ...,
            labels: google.protobuf.wrappers_pb2.StringValue | None = ...,
            assignee_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            state_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_assignee_id", b"_assignee_id", "_labels", b"_labels", "_priority", b"_priority", "_state_id", b"_state_id", "assignee_id", b"assignee_id", "description", b"description", "labels", b"labels", "priority", b"priority", "state_id", b"state_id", "team_id", b"team_id", "title", b"title"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_assignee_id", b"_assignee_id", "_labels", b"_labels", "_priority", b"_priority", "_state_id", b"_state_id", "assignee_id", b"assignee_id", "description", b"description", "labels", b"labels", "priority", b"priority", "state_id", b"state_id", "team_id", b"team_id", "title", b"title"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_assignee_id", b"_assignee_id"]) -> typing_extensions.Literal["assignee_id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_labels", b"_labels"]) -> typing_extensions.Literal["labels"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_priority", b"_priority"]) -> typing_extensions.Literal["priority"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_state_id", b"_state_id"]) -> typing_extensions.Literal["state_id"] | None: ...

    @typing_extensions.final
    class AssignIssue(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ISSUE_ID_FIELD_NUMBER: builtins.int
        ASSIGNEE_ID_FIELD_NUMBER: builtins.int
        @property
        def issue_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def assignee_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            issue_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            assignee_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["assignee_id", b"assignee_id", "issue_id", b"issue_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["assignee_id", b"assignee_id", "issue_id", b"issue_id"]) -> None: ...

    @typing_extensions.final
    class GetUsers(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        QUERY_FIELD_NUMBER: builtins.int
        @property
        def query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            query: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_query", b"_query", "query", b"query"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_query", b"_query", "query", b"query"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_query", b"_query"]) -> typing_extensions.Literal["query"] | None: ...

    @typing_extensions.final
    class GetIssue(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ISSUE_ID_FIELD_NUMBER: builtins.int
        @property
        def issue_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            issue_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["issue_id", b"issue_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["issue_id", b"issue_id"]) -> None: ...

    @typing_extensions.final
    class SearchIssues(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        QUERY_FIELD_NUMBER: builtins.int
        @property
        def query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            query: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_query", b"_query", "query", b"query"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_query", b"_query", "query", b"query"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_query", b"_query"]) -> typing_extensions.Literal["query"] | None: ...

    @typing_extensions.final
    class AddComment(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ISSUE_ID_FIELD_NUMBER: builtins.int
        COMMENT_TEXT_FIELD_NUMBER: builtins.int
        @property
        def issue_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def comment_text(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            issue_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            comment_text: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["comment_text", b"comment_text", "issue_id", b"issue_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["comment_text", b"comment_text", "issue_id", b"issue_id"]) -> None: ...

    @typing_extensions.final
    class GetTeams(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing_extensions.final
    class GetWorkflowStates(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEAM_ID_FIELD_NUMBER: builtins.int
        @property
        def team_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            team_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_team_id", b"_team_id", "team_id", b"team_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_team_id", b"_team_id", "team_id", b"team_id"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_team_id", b"_team_id"]) -> typing_extensions.Literal["team_id"] | None: ...

    TYPE_FIELD_NUMBER: builtins.int
    CREATE_ISSUE_FIELD_NUMBER: builtins.int
    ASSIGN_ISSUE_FIELD_NUMBER: builtins.int
    GET_USERS_FIELD_NUMBER: builtins.int
    GET_ISSUE_FIELD_NUMBER: builtins.int
    SEARCH_ISSUES_FIELD_NUMBER: builtins.int
    ADD_COMMENT_FIELD_NUMBER: builtins.int
    GET_TEAMS_FIELD_NUMBER: builtins.int
    GET_WORKFLOW_STATES_FIELD_NUMBER: builtins.int
    type: global___Linear.TaskType.ValueType
    @property
    def create_issue(self) -> global___Linear.CreateIssue: ...
    @property
    def assign_issue(self) -> global___Linear.AssignIssue: ...
    @property
    def get_users(self) -> global___Linear.GetUsers: ...
    @property
    def get_issue(self) -> global___Linear.GetIssue: ...
    @property
    def search_issues(self) -> global___Linear.SearchIssues: ...
    @property
    def add_comment(self) -> global___Linear.AddComment: ...
    @property
    def get_teams(self) -> global___Linear.GetTeams: ...
    @property
    def get_workflow_states(self) -> global___Linear.GetWorkflowStates: ...
    def __init__(
        self,
        *,
        type: global___Linear.TaskType.ValueType = ...,
        create_issue: global___Linear.CreateIssue | None = ...,
        assign_issue: global___Linear.AssignIssue | None = ...,
        get_users: global___Linear.GetUsers | None = ...,
        get_issue: global___Linear.GetIssue | None = ...,
        search_issues: global___Linear.SearchIssues | None = ...,
        add_comment: global___Linear.AddComment | None = ...,
        get_teams: global___Linear.GetTeams | None = ...,
        get_workflow_states: global___Linear.GetWorkflowStates | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["add_comment", b"add_comment", "assign_issue", b"assign_issue", "create_issue", b"create_issue", "get_issue", b"get_issue", "get_teams", b"get_teams", "get_users", b"get_users", "get_workflow_states", b"get_workflow_states", "search_issues", b"search_issues", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["add_comment", b"add_comment", "assign_issue", b"assign_issue", "create_issue", b"create_issue", "get_issue", b"get_issue", "get_teams", b"get_teams", "get_users", b"get_users", "get_workflow_states", b"get_workflow_states", "search_issues", b"search_issues", "task", b"task", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task", b"task"]) -> typing_extensions.Literal["create_issue", "assign_issue", "get_users", "get_issue", "search_issues", "add_comment", "get_teams", "get_workflow_states"] | None: ...

global___Linear = Linear
