"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.connectors.api_pb2
import core.protos.usage_and_billing.usage_and_billing_commons_pb2
import core.protos.usage_and_billing.usage_and_billing_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetBillingRemainingRequest(google.protobuf.message.Message):
    """Request for remaining credits"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["meta", b"meta"]) -> None: ...

global___GetBillingRemainingRequest = GetBillingRemainingRequest

@typing.final
class GetBillingRemainingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    REMAINING_CREDITS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def remaining_credits(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        remaining_credits: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta", "remaining_credits", b"remaining_credits", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "remaining_credits", b"remaining_credits", "success", b"success"]) -> None: ...

global___GetBillingRemainingResponse = GetBillingRemainingResponse

@typing.final
class GetBillingUsageMetricsRequest(google.protobuf.message.Message):
    """Request for usage metrics"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    CREDIT_TYPE_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def start_date(self) -> google.protobuf.wrappers_pb2.StringValue:
        """Optional date filters in YYYY-MM-DD format."""

    @property
    def end_date(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def credit_type(self) -> google.protobuf.wrappers_pb2.UInt32Value:
        """Optional credit type (use numeric enum value from CreditType)"""

    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        start_date: google.protobuf.wrappers_pb2.StringValue | None = ...,
        end_date: google.protobuf.wrappers_pb2.StringValue | None = ...,
        credit_type: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credit_type", b"credit_type", "end_date", b"end_date", "meta", b"meta", "start_date", b"start_date"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credit_type", b"credit_type", "end_date", b"end_date", "meta", b"meta", "start_date", b"start_date"]) -> None: ...

global___GetBillingUsageMetricsRequest = GetBillingUsageMetricsRequest

@typing.final
class GetBillingUsageMetricsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def metrics(self) -> core.protos.usage_and_billing.usage_and_billing_commons_pb2.BillingUsageMetrics: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        metrics: core.protos.usage_and_billing.usage_and_billing_commons_pb2.BillingUsageMetrics | None = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta", "metrics", b"metrics", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "metrics", b"metrics", "success", b"success"]) -> None: ...

global___GetBillingUsageMetricsResponse = GetBillingUsageMetricsResponse

@typing.final
class GetBillingUsageDistributionRequest(google.protobuf.message.Message):
    """Request for usage distribution"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    CREDIT_TYPE_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def start_date(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def end_date(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def credit_type(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        start_date: google.protobuf.wrappers_pb2.StringValue | None = ...,
        end_date: google.protobuf.wrappers_pb2.StringValue | None = ...,
        credit_type: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credit_type", b"credit_type", "end_date", b"end_date", "meta", b"meta", "start_date", b"start_date"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credit_type", b"credit_type", "end_date", b"end_date", "meta", b"meta", "start_date", b"start_date"]) -> None: ...

global___GetBillingUsageDistributionRequest = GetBillingUsageDistributionRequest

@typing.final
class GetBillingUsageDistributionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    DISTRIBUTION_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def distribution(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.usage_and_billing.usage_and_billing_commons_pb2.BillingUsageDistributionGroup]: ...
    def __init__(
        self,
        *,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        distribution: collections.abc.Iterable[core.protos.usage_and_billing.usage_and_billing_commons_pb2.BillingUsageDistributionGroup] | None = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["distribution", b"distribution", "message", b"message", "success", b"success"]) -> None: ...

global___GetBillingUsageDistributionResponse = GetBillingUsageDistributionResponse

@typing.final
class GetCreditUsageListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["meta", b"meta"]) -> None: ...

global___GetCreditUsageListRequest = GetCreditUsageListRequest

@typing.final
class GetCreditUsageListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    USAGE_BY_SESSION_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def usage_by_session(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.usage_and_billing.usage_and_billing_pb2.CreditUsageBySession]: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        usage_by_session: collections.abc.Iterable[core.protos.usage_and_billing.usage_and_billing_pb2.CreditUsageBySession] | None = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "success", b"success", "usage_by_session", b"usage_by_session"]) -> None: ...

global___GetCreditUsageListResponse = GetCreditUsageListResponse
