"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import core.protos.usage_and_billing.usage_and_billing_commons_pb2
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreditTransaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    CREDITS_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    SESSION_TITLE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    type: core.protos.usage_and_billing.usage_and_billing_commons_pb2.CreditType.ValueType
    created_at: builtins.int
    @property
    def credits(self) -> google.protobuf.wrappers_pb2.DoubleValue:
        """Use a double to allow fractional credit values (e.g., 1.25 credits)"""

    @property
    def session_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def session_title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        type: core.protos.usage_and_billing.usage_and_billing_commons_pb2.CreditType.ValueType = ...,
        credits: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        session_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        session_title: google.protobuf.wrappers_pb2.StringValue | None = ...,
        created_at: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credits", b"credits", "session_id", b"session_id", "session_title", b"session_title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "credits", b"credits", "session_id", b"session_id", "session_title", b"session_title", "type", b"type"]) -> None: ...

global___CreditTransaction = CreditTransaction

@typing.final
class CreditUsageBySession(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    SESSION_TITLE_FIELD_NUMBER: builtins.int
    CREDITS_USED_FIELD_NUMBER: builtins.int
    @property
    def session_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def session_title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def credits_used(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    def __init__(
        self,
        *,
        session_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        session_title: google.protobuf.wrappers_pb2.StringValue | None = ...,
        credits_used: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credits_used", b"credits_used", "session_id", b"session_id", "session_title", b"session_title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credits_used", b"credits_used", "session_id", b"session_id", "session_title", b"session_title"]) -> None: ...

global___CreditUsageBySession = CreditUsageBySession
