# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/protos/usage_and_billing/usage_and_billing_commons.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'core/protos/usage_and_billing/usage_and_billing_commons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=core/protos/usage_and_billing/usage_and_billing_commons.proto\x12\x1d\x63ore.protos.usage_and_billing\x1a\x1egoogle/protobuf/wrappers.proto\"\xd1\x01\n\x13\x42illingUsageMetrics\x12>\n\x18\x61i_investigation_credits\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12@\n\x1a\x62rowser_automation_credits\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x38\n\x12total_credits_used\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"\x84\x01\n\x1d\x42illingUsageDistributionEntry\x12/\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0c\x63redits_used\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"\xbb\x01\n\x1d\x42illingUsageDistributionGroup\x12>\n\x0b\x63redit_type\x18\x01 \x01(\x0e\x32).core.protos.usage_and_billing.CreditType\x12Z\n\x14\x64istribution_entries\x18\x02 \x03(\x0b\x32<.core.protos.usage_and_billing.BillingUsageDistributionEntry*N\n\nCreditType\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\x14\n\x10\x41I_INVESTIGATION\x10\x01\x12\x16\n\x12\x42ROWSER_AUTOMATION\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.usage_and_billing.usage_and_billing_commons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREDITTYPE']._serialized_start=665
  _globals['_CREDITTYPE']._serialized_end=743
  _globals['_BILLINGUSAGEMETRICS']._serialized_start=129
  _globals['_BILLINGUSAGEMETRICS']._serialized_end=338
  _globals['_BILLINGUSAGEDISTRIBUTIONENTRY']._serialized_start=341
  _globals['_BILLINGUSAGEDISTRIBUTIONENTRY']._serialized_end=473
  _globals['_BILLINGUSAGEDISTRIBUTIONGROUP']._serialized_start=476
  _globals['_BILLINGUSAGEDISTRIBUTIONGROUP']._serialized_end=663
# @@protoc_insertion_point(module_scope)
