# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/protos/browser_automation/api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'core/protos/browser_automation/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from core.protos.connectors import api_pb2 as core_dot_protos_dot_connectors_dot_api__pb2
from core.protos.browser_automation import browser_automation_commons_pb2 as core_dot_protos_dot_browser__automation_dot_browser__automation__commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(core/protos/browser_automation/api.proto\x12\x1e\x63ore.protos.browser_automation\x1a\x1egoogle/protobuf/wrappers.proto\x1a core/protos/connectors/api.proto\x1a?core/protos/browser_automation/browser_automation_commons.proto\"X\n\x1dStartBrowserAutomationRequest\x12\x37\n\x11user_input_prompt\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"\xb4\x01\n\x1eStartBrowserAutomationResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x07message\x18\x02 \x01(\x0b\x32\x1f.core.protos.connectors.Message\x12\x33\n\rprompt_run_id\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"V\n\x1f\x42rowserAutomationDetailsRequest\x12\x33\n\rprompt_run_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"\xdf\x01\n BrowserAutomationDetailsResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x07message\x18\x02 \x01(\x0b\x32\x1f.core.protos.connectors.Message\x12\\\n\x1a\x62rowser_automation_details\x18\x03 \x01(\x0b\x32\x38.core.protos.browser_automation.BrowserAutomationDetails\"\xd5\x01\n\x1dSaveDataFromLightSaberRequest\x12>\n\x18investigation_session_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12G\n\x04type\x18\x03 \x01(\x0e\x32\x39.core.protos.browser_automation.BrowserAutomationDataType\"\x7f\n\x1eSaveDataFromLightSaberResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x07message\x18\x02 \x01(\x0b\x32\x1f.core.protos.connectors.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.browser_automation.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTBROWSERAUTOMATIONREQUEST']._serialized_start=207
  _globals['_STARTBROWSERAUTOMATIONREQUEST']._serialized_end=295
  _globals['_STARTBROWSERAUTOMATIONRESPONSE']._serialized_start=298
  _globals['_STARTBROWSERAUTOMATIONRESPONSE']._serialized_end=478
  _globals['_BROWSERAUTOMATIONDETAILSREQUEST']._serialized_start=480
  _globals['_BROWSERAUTOMATIONDETAILSREQUEST']._serialized_end=566
  _globals['_BROWSERAUTOMATIONDETAILSRESPONSE']._serialized_start=569
  _globals['_BROWSERAUTOMATIONDETAILSRESPONSE']._serialized_end=792
  _globals['_SAVEDATAFROMLIGHTSABERREQUEST']._serialized_start=795
  _globals['_SAVEDATAFROMLIGHTSABERREQUEST']._serialized_end=1008
  _globals['_SAVEDATAFROMLIGHTSABERRESPONSE']._serialized_start=1010
  _globals['_SAVEDATAFROMLIGHTSABERRESPONSE']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
