# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/protos/alert_metadata_details_commons.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'core/protos/alert_metadata_details_commons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0core/protos/alert_metadata_details_commons.proto\x12\x0b\x63ore.protos*}\n\rAlertSeverity\x12\x1a\n\x16\x41LERT_SEVERITY_UNKNOWN\x10\x00\x12\x17\n\x13\x41LERT_SEVERITY_INFO\x10\x01\x12\x1a\n\x16\x41LERT_SEVERITY_WARNING\x10\x02\x12\x1b\n\x17\x41LERT_SEVERITY_CRITICAL\x10\x04*\xe3\x01\n\x0b\x41lertStatus\x12\x18\n\x14\x41LERT_STATUS_UNKNOWN\x10\x00\x12\x14\n\x10\x41LERT_STATUS_NEW\x10\x01\x12\x1d\n\x19\x41LERT_STATUS_ACKNOWLEDGED\x10\x02\x12\x18\n\x14\x41LERT_STATUS_TRIAGED\x10\x03\x12\x1a\n\x16\x41LERT_STATUS_ESCALATED\x10\x04\x12\x1b\n\x17\x41LERT_STATUS_REMEDIATED\x10\x05\x12\x19\n\x15\x41LERT_STATUS_RESOLVED\x10\x06\x12\x17\n\x13\x41LERT_STATUS_HIDDEN\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.alert_metadata_details_commons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTSEVERITY']._serialized_start=65
  _globals['_ALERTSEVERITY']._serialized_end=190
  _globals['_ALERTSTATUS']._serialized_start=193
  _globals['_ALERTSTATUS']._serialized_end=420
# @@protoc_insertion_point(module_scope)
