# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/protos/alert_metadata_details.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'core/protos/alert_metadata_details.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.protos import alert_metadata_details_commons_pb2 as core_dot_protos_dot_alert__metadata__details__commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(core/protos/alert_metadata_details.proto\x12\x0b\x63ore.protos\x1a\x30\x63ore/protos/alert_metadata_details_commons.proto\"z\n\x14\x41lertMetadataDetails\x12.\n\x0c\x61lert_status\x18\x01 \x01(\x0e\x32\x18.core.protos.AlertStatus\x12\x32\n\x0e\x61lert_severity\x18\x02 \x01(\x0e\x32\x1a.core.protos.AlertSeverityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.alert_metadata_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTMETADATADETAILS']._serialized_start=107
  _globals['_ALERTMETADATADETAILS']._serialized_end=229
# @@protoc_insertion_point(module_scope)
