"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import core.protos.alert_metadata_details_commons_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class AlertMetadataDetails(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALERT_STATUS_FIELD_NUMBER: builtins.int
    ALERT_SEVERITY_FIELD_NUMBER: builtins.int
    alert_status: core.protos.alert_metadata_details_commons_pb2.AlertStatus.ValueType
    alert_severity: core.protos.alert_metadata_details_commons_pb2.AlertSeverity.ValueType
    def __init__(
        self,
        *,
        alert_status: core.protos.alert_metadata_details_commons_pb2.AlertStatus.ValueType = ...,
        alert_severity: core.protos.alert_metadata_details_commons_pb2.AlertSeverity.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["alert_severity", b"alert_severity", "alert_status", b"alert_status"]) -> None: ...

global___AlertMetadataDetails = AlertMetadataDetails
