from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Function(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN_F: _ClassVar[Function]
    AVG_F: _ClassVar[Function]
    SUM_F: _ClassVar[Function]
    MIN_F: _ClassVar[Function]
    MAX_F: _ClassVar[Function]
    LAST_F: _ClassVar[Function]

class Operator(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN_O: _ClassVar[Operator]
    GREATER_THAN_O: _ClassVar[Operator]
    GREATER_THAN_EQUAL_O: _ClassVar[Operator]
    LESS_THAN_O: _ClassVar[Operator]
    LESS_THAN_EQUAL_O: _ClassVar[Operator]
    EQUAL_O: _ClassVar[Operator]
    NOT_EQUAL_O: _ClassVar[Operator]
    LIKE_O: _ClassVar[Operator]
    EXISTS_O: _ClassVar[Operator]
    CONTAINS_O: _ClassVar[Operator]

class LogicalOperator(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN_LO: _ClassVar[LogicalOperator]
    AND_LO: _ClassVar[LogicalOperator]
    OR_LO: _ClassVar[LogicalOperator]
    NOT_LO: _ClassVar[LogicalOperator]

class Op(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN_OP: _ClassVar[Op]
    EQ: _ClassVar[Op]
    NEQ: _ClassVar[Op]
    GT: _ClassVar[Op]
    LT: _ClassVar[Op]
    GTE: _ClassVar[Op]
    LTE: _ClassVar[Op]
    IN: _ClassVar[Op]
    NOT_IN: _ClassVar[Op]
    IS_NULL: _ClassVar[Op]
    EXISTS: _ClassVar[Op]
    AND: _ClassVar[Op]
    OR: _ClassVar[Op]
    NOT: _ClassVar[Op]

class Source(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN: _ClassVar[Source]
    SENTRY: _ClassVar[Source]
    SEGMENT: _ClassVar[Source]
    ELASTIC_SEARCH: _ClassVar[Source]
    AMPLITUDE: _ClassVar[Source]
    AWS_KINESIS: _ClassVar[Source]
    CLOUDWATCH: _ClassVar[Source]
    CLEVERTAP: _ClassVar[Source]
    RUDDERSTACK: _ClassVar[Source]
    MOENGAGE: _ClassVar[Source]
    CRIBL: _ClassVar[Source]
    KAFKA: _ClassVar[Source]
    DATADOG: _ClassVar[Source]
    FILEBEAT: _ClassVar[Source]
    LOGSTASH: _ClassVar[Source]
    FLUENTD: _ClassVar[Source]
    FLUENTBIT: _ClassVar[Source]
    PAGER_DUTY: _ClassVar[Source]
    NEW_RELIC: _ClassVar[Source]
    SLACK: _ClassVar[Source]
    HONEYBADGER: _ClassVar[Source]
    GOOGLE_CHAT: _ClassVar[Source]
    DATADOG_OAUTH: _ClassVar[Source]
    GCM: _ClassVar[Source]
    PROMETHEUS: _ClassVar[Source]
    ELASTIC_APM: _ClassVar[Source]
    VICTORIA_METRICS: _ClassVar[Source]
    SLACK_CONNECT: _ClassVar[Source]
    GRAFANA: _ClassVar[Source]
    CLICKHOUSE: _ClassVar[Source]
    DOCUMENTATION: _ClassVar[Source]
    POSTGRES: _ClassVar[Source]
    OPS_GENIE: _ClassVar[Source]
    EKS: _ClassVar[Source]
    AGENT_PROXY: _ClassVar[Source]
    GRAFANA_VPC: _ClassVar[Source]
    GITHUB: _ClassVar[Source]
    SQL_DATABASE_CONNECTION: _ClassVar[Source]
    OPEN_AI: _ClassVar[Source]
    REMOTE_SERVER: _ClassVar[Source]
    API: _ClassVar[Source]
    BASH: _ClassVar[Source]
    AZURE: _ClassVar[Source]
    GRAFANA_MIMIR: _ClassVar[Source]
    GKE: _ClassVar[Source]
    MS_TEAMS: _ClassVar[Source]
    GRAFANA_LOKI: _ClassVar[Source]
    KUBERNETES: _ClassVar[Source]
    SMTP: _ClassVar[Source]
    BIG_QUERY: _ClassVar[Source]
    ZENDUTY: _ClassVar[Source]
    ROOTLY: _ClassVar[Source]
    JIRA_CLOUD: _ClassVar[Source]
    ASANA: _ClassVar[Source]
    CONFLUENCE_CLOUD: _ClassVar[Source]
    CONFLUENCE_SELF_HOSTED: _ClassVar[Source]
    GOOGLE_DRIVE: _ClassVar[Source]
    NOTION: _ClassVar[Source]
    DRD_PROXY_AGENT: _ClassVar[Source]
    MONGODB: _ClassVar[Source]
    OPEN_SEARCH: _ClassVar[Source]
    LINEAR: _ClassVar[Source]
    JENKINS: _ClassVar[Source]
    GITHUB_ACTIONS: _ClassVar[Source]
    CUSTOM_STRATEGIES: _ClassVar[Source]
    ARGOCD: _ClassVar[Source]
    DRD_ALERT_WEBHOOK: _ClassVar[Source]
    ROLLBAR: _ClassVar[Source]
    LAMBDA: _ClassVar[Source]
    BROWSER: _ClassVar[Source]
    POSTHOG: _ClassVar[Source]
    MIXPANEL: _ClassVar[Source]
    SIGNOZ: _ClassVar[Source]
    BITBUCKET: _ClassVar[Source]
    CORALOGIX: _ClassVar[Source]
    RENDER: _ClassVar[Source]
    MCP_SERVER: _ClassVar[Source]
    VICTORIA_LOGS: _ClassVar[Source]
    METABASE: _ClassVar[Source]

class SourceKeyType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN_SKT: _ClassVar[SourceKeyType]
    SENTRY_API_KEY: _ClassVar[SourceKeyType]
    SENTRY_ORG_SLUG: _ClassVar[SourceKeyType]
    DATADOG_APP_KEY: _ClassVar[SourceKeyType]
    DATADOG_API_KEY: _ClassVar[SourceKeyType]
    DATADOG_AUTH_TOKEN: _ClassVar[SourceKeyType]
    DATADOG_API_DOMAIN: _ClassVar[SourceKeyType]
    NEWRELIC_API_KEY: _ClassVar[SourceKeyType]
    NEWRELIC_APP_ID: _ClassVar[SourceKeyType]
    NEWRELIC_QUERY_KEY: _ClassVar[SourceKeyType]
    NEWRELIC_API_DOMAIN: _ClassVar[SourceKeyType]
    SLACK_BOT_AUTH_TOKEN: _ClassVar[SourceKeyType]
    SLACK_CHANNEL_SKT: _ClassVar[SourceKeyType]
    SLACK_APP_ID: _ClassVar[SourceKeyType]
    SLACK_APP_CLIENT_ID: _ClassVar[SourceKeyType]
    SLACK_APP_CLIENT_SECRET: _ClassVar[SourceKeyType]
    SLACK_APP_SIGNING_SECRET: _ClassVar[SourceKeyType]
    HONEYBADGER_USERNAME: _ClassVar[SourceKeyType]
    HONEYBADGER_PASSWORD: _ClassVar[SourceKeyType]
    HONEYBADGER_PROJECT_ID: _ClassVar[SourceKeyType]
    AWS_ACCESS_KEY: _ClassVar[SourceKeyType]
    AWS_SECRET_KEY: _ClassVar[SourceKeyType]
    AWS_REGION: _ClassVar[SourceKeyType]
    AWS_ASSUMED_ROLE_ARN: _ClassVar[SourceKeyType]
    EKS_ROLE_ARN: _ClassVar[SourceKeyType]
    AWS_DRD_CLOUD_ROLE_ARN: _ClassVar[SourceKeyType]
    GOOGLE_CHAT_BOT_OAUTH_TOKEN: _ClassVar[SourceKeyType]
    GOOGLE_CHAT_BOT_SPACES: _ClassVar[SourceKeyType]
    GRAFANA_HOST: _ClassVar[SourceKeyType]
    GRAFANA_API_KEY: _ClassVar[SourceKeyType]
    GRAFANA_TEAM_HOST: _ClassVar[SourceKeyType]
    CLICKHOUSE_INTERFACE: _ClassVar[SourceKeyType]
    CLICKHOUSE_HOST: _ClassVar[SourceKeyType]
    CLICKHOUSE_PORT: _ClassVar[SourceKeyType]
    CLICKHOUSE_USER: _ClassVar[SourceKeyType]
    CLICKHOUSE_PASSWORD: _ClassVar[SourceKeyType]
    GCM_PROJECT_ID: _ClassVar[SourceKeyType]
    GCM_PRIVATE_KEY: _ClassVar[SourceKeyType]
    GCM_CLIENT_EMAIL: _ClassVar[SourceKeyType]
    GCM_TOKEN_URI: _ClassVar[SourceKeyType]
    GCM_SERVICE_ACCOUNT_JSON: _ClassVar[SourceKeyType]
    POSTGRES_HOST: _ClassVar[SourceKeyType]
    POSTGRES_USER: _ClassVar[SourceKeyType]
    POSTGRES_PASSWORD: _ClassVar[SourceKeyType]
    POSTGRES_PORT: _ClassVar[SourceKeyType]
    POSTGRES_DATABASE: _ClassVar[SourceKeyType]
    POSTGRES_OPTIONS: _ClassVar[SourceKeyType]
    SQL_DATABASE_CONNECTION_STRING_URI: _ClassVar[SourceKeyType]
    PAGER_DUTY_API_KEY: _ClassVar[SourceKeyType]
    PAGER_DUTY_CONFIGURED_EMAIL: _ClassVar[SourceKeyType]
    OPS_GENIE_API_KEY: _ClassVar[SourceKeyType]
    AGENT_PROXY_HOST: _ClassVar[SourceKeyType]
    AGENT_PROXY_API_KEY: _ClassVar[SourceKeyType]
    GITHUB_TOKEN: _ClassVar[SourceKeyType]
    GITHUB_ORG: _ClassVar[SourceKeyType]
    OPEN_AI_API_KEY: _ClassVar[SourceKeyType]
    REMOTE_SERVER_PEM: _ClassVar[SourceKeyType]
    REMOTE_SERVER_USER: _ClassVar[SourceKeyType]
    REMOTE_SERVER_HOST: _ClassVar[SourceKeyType]
    REMOTE_SERVER_PASSWORD: _ClassVar[SourceKeyType]
    REMOTE_SERVER_PORT: _ClassVar[SourceKeyType]
    MIMIR_HOST: _ClassVar[SourceKeyType]
    X_SCOPE_ORG_ID: _ClassVar[SourceKeyType]
    SSL_VERIFY: _ClassVar[SourceKeyType]
    AZURE_SUBSCRIPTION_ID: _ClassVar[SourceKeyType]
    AZURE_TENANT_ID: _ClassVar[SourceKeyType]
    AZURE_CLIENT_ID: _ClassVar[SourceKeyType]
    AZURE_CLIENT_SECRET: _ClassVar[SourceKeyType]
    GKE_PROJECT_ID: _ClassVar[SourceKeyType]
    GKE_SERVICE_ACCOUNT_JSON: _ClassVar[SourceKeyType]
    MS_TEAMS_CONNECTOR_WEBHOOK_URL: _ClassVar[SourceKeyType]
    ELASTIC_SEARCH_PROTOCOL: _ClassVar[SourceKeyType]
    ELASTIC_SEARCH_HOST: _ClassVar[SourceKeyType]
    ELASTIC_SEARCH_PORT: _ClassVar[SourceKeyType]
    ELASTIC_SEARCH_API_KEY_ID: _ClassVar[SourceKeyType]
    ELASTIC_SEARCH_API_KEY: _ClassVar[SourceKeyType]
    GRAFANA_LOKI_PROTOCOL: _ClassVar[SourceKeyType]
    GRAFANA_LOKI_HOST: _ClassVar[SourceKeyType]
    GRAFANA_LOKI_PORT: _ClassVar[SourceKeyType]
    KUBERNETES_CLUSTER_NAME: _ClassVar[SourceKeyType]
    KUBERNETES_CLUSTER_API_SERVER: _ClassVar[SourceKeyType]
    KUBERNETES_CLUSTER_TOKEN: _ClassVar[SourceKeyType]
    KUBERNETES_CLUSTER_CERTIFICATE_AUTHORITY_DATA: _ClassVar[SourceKeyType]
    KUBERNETES_CLUSTER_CERTIFICATE_AUTHORITY_PATH: _ClassVar[SourceKeyType]
    SMTP_HOST: _ClassVar[SourceKeyType]
    SMTP_PORT: _ClassVar[SourceKeyType]
    SMTP_USER: _ClassVar[SourceKeyType]
    SMTP_PASSWORD: _ClassVar[SourceKeyType]
    BIG_QUERY_PROJECT_ID: _ClassVar[SourceKeyType]
    BIG_QUERY_SERVICE_ACCOUNT_JSON: _ClassVar[SourceKeyType]
    ZENDUTY_API_KEY: _ClassVar[SourceKeyType]
    ROOTLY_API_KEY: _ClassVar[SourceKeyType]
    JIRA_CLOUD_API_KEY: _ClassVar[SourceKeyType]
    JIRA_DOMAIN: _ClassVar[SourceKeyType]
    JIRA_EMAIL: _ClassVar[SourceKeyType]
    ASANA_ACCESS_TOKEN: _ClassVar[SourceKeyType]
    CONFLUENCE_CLOUD_API_KEY: _ClassVar[SourceKeyType]
    CONFLUENCE_CLOUD_SITE_URL: _ClassVar[SourceKeyType]
    CONFLUENCE_CLOUD_ATLASSIAN_ACCOUNT_EMAIL: _ClassVar[SourceKeyType]
    NOTION_API_KEY: _ClassVar[SourceKeyType]
    DRD_PROXY_AGENT_HOST: _ClassVar[SourceKeyType]
    DRD_PROXY_AGENT_API_TOKEN: _ClassVar[SourceKeyType]
    DRD_PROXY_AGENT_API_KEY: _ClassVar[SourceKeyType]
    MONGODB_CONNECTION_STRING: _ClassVar[SourceKeyType]
    OPEN_SEARCH_PROTOCOL: _ClassVar[SourceKeyType]
    OPEN_SEARCH_HOST: _ClassVar[SourceKeyType]
    OPEN_SEARCH_PORT: _ClassVar[SourceKeyType]
    OPEN_SEARCH_USERNAME: _ClassVar[SourceKeyType]
    OPEN_SEARCH_PASSWORD: _ClassVar[SourceKeyType]
    LINEAR_API_KEY: _ClassVar[SourceKeyType]
    JENKINS_URL: _ClassVar[SourceKeyType]
    JENKINS_USERNAME: _ClassVar[SourceKeyType]
    JENKINS_API_TOKEN: _ClassVar[SourceKeyType]
    JENKINS_CRUMB: _ClassVar[SourceKeyType]
    GITHUB_ACTIONS_TOKEN: _ClassVar[SourceKeyType]
    CUSTOM_STRATEGIES_ACCOUNT_ID: _ClassVar[SourceKeyType]
    ARGOCD_SERVER: _ClassVar[SourceKeyType]
    ARGOCD_TOKEN: _ClassVar[SourceKeyType]
    ROLLBAR_ACCESS_TOKEN: _ClassVar[SourceKeyType]
    POSTHOG_API_KEY: _ClassVar[SourceKeyType]
    POSTHOG_APP_HOST: _ClassVar[SourceKeyType]
    POSTHOG_PROJECT_ID: _ClassVar[SourceKeyType]
    MIXPANEL_SERVICE_ACCOUNT_USERNAME: _ClassVar[SourceKeyType]
    MIXPANEL_SERVICE_ACCOUNT_SECRET: _ClassVar[SourceKeyType]
    MIXPANEL_DOMAIN: _ClassVar[SourceKeyType]
    MIXPANEL_PROJECT_ID: _ClassVar[SourceKeyType]
    MIXPANEL_WORKSPACE_ID: _ClassVar[SourceKeyType]
    SIGNOZ_API_URL: _ClassVar[SourceKeyType]
    SIGNOZ_API_TOKEN: _ClassVar[SourceKeyType]
    KIBANA_HOST: _ClassVar[SourceKeyType]
    BITBUCKET_WORKSPACE: _ClassVar[SourceKeyType]
    BITBUCKET_API_KEY: _ClassVar[SourceKeyType]
    BITBUCKET_REPO: _ClassVar[SourceKeyType]
    RENDER_API_KEY: _ClassVar[SourceKeyType]
    CORALOGIX_API_KEY: _ClassVar[SourceKeyType]
    CORALOGIX_ENDPOINT: _ClassVar[SourceKeyType]
    CORALOGIX_DOMAIN: _ClassVar[SourceKeyType]
    MCP_SERVER_BASE_URL: _ClassVar[SourceKeyType]
    MCP_SERVER_AUTH_HEADERS: _ClassVar[SourceKeyType]
    VICTORIA_LOGS_PROTOCOL: _ClassVar[SourceKeyType]
    VICTORIA_LOGS_HOST: _ClassVar[SourceKeyType]
    VICTORIA_LOGS_PORT: _ClassVar[SourceKeyType]
    VICTORIA_LOGS_HEADERS: _ClassVar[SourceKeyType]
    GITHUB_APP_ID: _ClassVar[SourceKeyType]
    GITHUB_APP_PRIVATE_KEY: _ClassVar[SourceKeyType]
    GITHUB_APP_INSTALLATION_ID: _ClassVar[SourceKeyType]
    GITHUB_APP_ACCESS_TOKEN: _ClassVar[SourceKeyType]
    METABASE_URL: _ClassVar[SourceKeyType]
    METABASE_API_KEY: _ClassVar[SourceKeyType]

class SourceModelType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN_MT: _ClassVar[SourceModelType]
    NEW_RELIC_POLICY: _ClassVar[SourceModelType]
    NEW_RELIC_CONDITION: _ClassVar[SourceModelType]
    NEW_RELIC_ENTITY: _ClassVar[SourceModelType]
    NEW_RELIC_ENTITY_DASHBOARD: _ClassVar[SourceModelType]
    NEW_RELIC_ENTITY_APPLICATION: _ClassVar[SourceModelType]
    NEW_RELIC_NRQL: _ClassVar[SourceModelType]
    NEW_RELIC_ENTITY_DASHBOARD_V2: _ClassVar[SourceModelType]
    DATADOG_MONITOR: _ClassVar[SourceModelType]
    DATADOG_DASHBOARD: _ClassVar[SourceModelType]
    DATADOG_LIVE_INTEGRATION_AWS: _ClassVar[SourceModelType]
    DATADOG_LIVE_INTEGRATION_AWS_LOG: _ClassVar[SourceModelType]
    DATADOG_LIVE_INTEGRATION_AZURE: _ClassVar[SourceModelType]
    DATADOG_LIVE_INTEGRATION_CLOUDFLARE: _ClassVar[SourceModelType]
    DATADOG_LIVE_INTEGRATION_FASTLY: _ClassVar[SourceModelType]
    DATADOG_LIVE_INTEGRATION_GCP: _ClassVar[SourceModelType]
    DATADOG_LIVE_INTEGRATION_CONFLUENT: _ClassVar[SourceModelType]
    DATADOG_SERVICE: _ClassVar[SourceModelType]
    DATADOG_METRIC: _ClassVar[SourceModelType]
    DATADOG_QUERY: _ClassVar[SourceModelType]
    DATADOG_APM: _ClassVar[SourceModelType]
    DATADOG_FIELDS: _ClassVar[SourceModelType]
    CLOUDWATCH_METRIC: _ClassVar[SourceModelType]
    CLOUDWATCH_LOG_GROUP: _ClassVar[SourceModelType]
    CLOUDWATCH_LOG_GROUP_QUERY: _ClassVar[SourceModelType]
    CLOUDWATCH_ALARMS: _ClassVar[SourceModelType]
    RDS_INSTANCES: _ClassVar[SourceModelType]
    CLOUDWATCH_DASHBOARD: _ClassVar[SourceModelType]
    GRAFANA_DATASOURCE: _ClassVar[SourceModelType]
    GRAFANA_DASHBOARD: _ClassVar[SourceModelType]
    GRAFANA_TARGET_METRIC_PROMQL: _ClassVar[SourceModelType]
    GRAFANA_PROMETHEUS_DATASOURCE: _ClassVar[SourceModelType]
    GRAFANA_ALERT_RULE: _ClassVar[SourceModelType]
    GRAFANA_LOKI_DATASOURCE: _ClassVar[SourceModelType]
    CLICKHOUSE_DATABASE: _ClassVar[SourceModelType]
    CLICKHOUSE_TABLE: _ClassVar[SourceModelType]
    SLACK_CHANNEL: _ClassVar[SourceModelType]
    MARKDOWN: _ClassVar[SourceModelType]
    IFRAME: _ClassVar[SourceModelType]
    POSTGRES_QUERY: _ClassVar[SourceModelType]
    POSTGRES_TABLE: _ClassVar[SourceModelType]
    EKS_CLUSTER: _ClassVar[SourceModelType]
    EKS_NAMESPACE: _ClassVar[SourceModelType]
    EKS_SERVICE: _ClassVar[SourceModelType]
    EKS_DEPLOYMENT: _ClassVar[SourceModelType]
    EKS_INGRESS: _ClassVar[SourceModelType]
    EKS_NETWORK_POLICY: _ClassVar[SourceModelType]
    EKS_HPA: _ClassVar[SourceModelType]
    EKS_REPLICASET: _ClassVar[SourceModelType]
    EKS_STATEFULSET: _ClassVar[SourceModelType]
    SQL_DATABASE_CONNECTION_RAW_QUERY: _ClassVar[SourceModelType]
    SQL_DATABASE_TABLE: _ClassVar[SourceModelType]
    AZURE_WORKSPACE: _ClassVar[SourceModelType]
    AZURE_RESOURCE: _ClassVar[SourceModelType]
    AZURE_AKS_CLUSTER: _ClassVar[SourceModelType]
    AZURE_AKS_NAMESPACE: _ClassVar[SourceModelType]
    AZURE_AKS_DEPLOYMENT: _ClassVar[SourceModelType]
    AZURE_AKS_SERVICE: _ClassVar[SourceModelType]
    AZURE_AKS_INGRESS: _ClassVar[SourceModelType]
    AZURE_AKS_NETWORK_POLICY: _ClassVar[SourceModelType]
    AZURE_AKS_HPA: _ClassVar[SourceModelType]
    AZURE_AKS_REPLICASET: _ClassVar[SourceModelType]
    AZURE_AKS_STATEFULSET: _ClassVar[SourceModelType]
    AZURE_VIRTUAL_MACHINE: _ClassVar[SourceModelType]
    AZURE_VMSS: _ClassVar[SourceModelType]
    AZURE_STORAGE_ACCOUNT: _ClassVar[SourceModelType]
    AZURE_BLOB_CONTAINER: _ClassVar[SourceModelType]
    AZURE_SQL_SERVER: _ClassVar[SourceModelType]
    AZURE_SQL_DATABASE: _ClassVar[SourceModelType]
    AZURE_COSMOS_ACCOUNT: _ClassVar[SourceModelType]
    AZURE_POSTGRES_SERVER: _ClassVar[SourceModelType]
    AZURE_POSTGRES_DATABASE: _ClassVar[SourceModelType]
    AZURE_METRIC_ALERT: _ClassVar[SourceModelType]
    AZURE_ACTION_GROUP: _ClassVar[SourceModelType]
    AZURE_RESOURCE_GROUP: _ClassVar[SourceModelType]
    AZURE_REDIS_CACHE: _ClassVar[SourceModelType]
    SSH_SERVER: _ClassVar[SourceModelType]
    SSH_USER: _ClassVar[SourceModelType]
    GRAFANA_MIMIR_PROMQL: _ClassVar[SourceModelType]
    GKE_CLUSTER: _ClassVar[SourceModelType]
    GKE_NAMESPACE: _ClassVar[SourceModelType]
    GKE_SERVICE: _ClassVar[SourceModelType]
    GKE_DEPLOYMENT: _ClassVar[SourceModelType]
    GKE_INGRESS: _ClassVar[SourceModelType]
    GKE_NETWORK_POLICY: _ClassVar[SourceModelType]
    GKE_HPA: _ClassVar[SourceModelType]
    GKE_REPLICASET: _ClassVar[SourceModelType]
    GKE_STATEFULSET: _ClassVar[SourceModelType]
    GCP_COMPUTE_INSTANCE: _ClassVar[SourceModelType]
    GCP_INSTANCE_GROUP: _ClassVar[SourceModelType]
    GCP_STORAGE_BUCKET: _ClassVar[SourceModelType]
    GCP_CLOUD_SQL_INSTANCE: _ClassVar[SourceModelType]
    GCP_CLOUD_SQL_DATABASE: _ClassVar[SourceModelType]
    GCP_MEMORYSTORE_REDIS: _ClassVar[SourceModelType]
    GCP_ALERT_POLICY: _ClassVar[SourceModelType]
    GCP_NOTIFICATION_CHANNEL: _ClassVar[SourceModelType]
    GCP_CLOUD_FUNCTION: _ClassVar[SourceModelType]
    GCP_CLOUD_RUN_SERVICE: _ClassVar[SourceModelType]
    GCP_PUBSUB_TOPIC: _ClassVar[SourceModelType]
    GCP_PUBSUB_SUBSCRIPTION: _ClassVar[SourceModelType]
    GCP_BIGQUERY_DATASET: _ClassVar[SourceModelType]
    GCP_BIGQUERY_TABLE: _ClassVar[SourceModelType]
    GCP_VPC_NETWORK: _ClassVar[SourceModelType]
    GCP_SUBNETWORK: _ClassVar[SourceModelType]
    GCP_FIREWALL_RULE: _ClassVar[SourceModelType]
    GCP_LOAD_BALANCER: _ClassVar[SourceModelType]
    GCP_SECRET: _ClassVar[SourceModelType]
    GCP_SERVICE_ACCOUNT: _ClassVar[SourceModelType]
    GCP_LOG_SINK: _ClassVar[SourceModelType]
    GCP_LOG_METRIC: _ClassVar[SourceModelType]
    MS_TEAMS_CHANNEL: _ClassVar[SourceModelType]
    PAGERDUTY_INCIDENT: _ClassVar[SourceModelType]
    ELASTIC_SEARCH_INDEX: _ClassVar[SourceModelType]
    ELASTIC_SEARCH_SERVICES: _ClassVar[SourceModelType]
    ELASTIC_SEARCH_DASHBOARDS: _ClassVar[SourceModelType]
    ELASTIC_SEARCH_INDEX_PATTERNS: _ClassVar[SourceModelType]
    GCM_METRIC: _ClassVar[SourceModelType]
    GCM_DASHBOARD: _ClassVar[SourceModelType]
    GCM_CLOUD_RUN_SERVICE_DASHBOARD: _ClassVar[SourceModelType]
    ZENDUTY_INCIDENT: _ClassVar[SourceModelType]
    ROOTLY_INCIDENT: _ClassVar[SourceModelType]
    OPS_GENIE_ESCALATION: _ClassVar[SourceModelType]
    OPS_GENIE_TEAM: _ClassVar[SourceModelType]
    GOOGLE_CHAT_SPACE: _ClassVar[SourceModelType]
    MONGODB_DATABASE: _ClassVar[SourceModelType]
    MONGODB_COLLECTION: _ClassVar[SourceModelType]
    OPEN_SEARCH_INDEX: _ClassVar[SourceModelType]
    ASANA_PROJECT: _ClassVar[SourceModelType]
    MODELS_ACTIVE: _ClassVar[SourceModelType]
    GITHUB_REPOSITORY: _ClassVar[SourceModelType]
    GITHUB_MEMBER: _ClassVar[SourceModelType]
    JIRA_PROJECT: _ClassVar[SourceModelType]
    JIRA_USER: _ClassVar[SourceModelType]
    ARGOCD_APPS: _ClassVar[SourceModelType]
    JENKINS_JOBS: _ClassVar[SourceModelType]
    POSTHOG_PERSON: _ClassVar[SourceModelType]
    POSTHOG_GROUP: _ClassVar[SourceModelType]
    POSTHOG_COHORT: _ClassVar[SourceModelType]
    POSTHOG_PROPERTY: _ClassVar[SourceModelType]
    ECS_CLUSTER: _ClassVar[SourceModelType]
    ECS_TASK: _ClassVar[SourceModelType]
    ECS_SERVICE: _ClassVar[SourceModelType]
    SIGNOZ_DASHBOARD: _ClassVar[SourceModelType]
    SIGNOZ_ALERT: _ClassVar[SourceModelType]
    SIGNOZ_METRIC: _ClassVar[SourceModelType]
    SIGNOZ_SERVICE: _ClassVar[SourceModelType]
    SIGNOZ_LOG_ATTRIBUTES: _ClassVar[SourceModelType]
    KUBERNETES_NAMESPACE: _ClassVar[SourceModelType]
    KUBERNETES_SERVICE: _ClassVar[SourceModelType]
    KUBERNETES_DEPLOYMENT: _ClassVar[SourceModelType]
    KUBERNETES_INGRESS: _ClassVar[SourceModelType]
    KUBERNETES_NETWORK_POLICY: _ClassVar[SourceModelType]
    KUBERNETES_HPA: _ClassVar[SourceModelType]
    KUBERNETES_REPLICASET: _ClassVar[SourceModelType]
    KUBERNETES_STATEFULSET: _ClassVar[SourceModelType]
    KUBERNETES_NETWORK_MAP: _ClassVar[SourceModelType]
    SENTRY_PROJECT: _ClassVar[SourceModelType]
    CORALOGIX_DASHBOARD: _ClassVar[SourceModelType]
    CORALOGIX_INDEX_MAPPING: _ClassVar[SourceModelType]
    VICTORIA_LOGS_FIELD: _ClassVar[SourceModelType]
    MCP_TOOLS: _ClassVar[SourceModelType]

class Context(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNKNOWN_C: _ClassVar[Context]
    EVENT: _ClassVar[Context]
    MONITOR_TRANSACTION: _ClassVar[Context]
    ENTITY_INSTANCE: _ClassVar[Context]
    EVENT_TYPE: _ClassVar[Context]
    MONITOR: _ClassVar[Context]
    ENTITY: _ClassVar[Context]
    EVENTS_CLICKHOUSE: _ClassVar[Context]
    PANEL_NAME: _ClassVar[Context]
    DASHBOARD_NAME: _ClassVar[Context]
    EVENTS_ALERT_OPS_CLICKHOUSE: _ClassVar[Context]
    SLACK_ALERT: _ClassVar[Context]
    EVENTS_PRODIGAL_CLICKHOUSE: _ClassVar[Context]
    ALERT_OPS: _ClassVar[Context]
    ALERT_MIDDLEWARE: _ClassVar[Context]

class RecentArtifactType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    RA_UNKNOWN: _ClassVar[RecentArtifactType]
    RA_GITHUB_REPO: _ClassVar[RecentArtifactType]
    RA_GITHUB_COMMIT: _ClassVar[RecentArtifactType]
    RA_GITHUB_PR: _ClassVar[RecentArtifactType]
    RA_GITHUB_RELEASE: _ClassVar[RecentArtifactType]
    RA_GITLAB_REPO: _ClassVar[RecentArtifactType]
    RA_GITLAB_COMMIT: _ClassVar[RecentArtifactType]
    RA_GITLAB_MR: _ClassVar[RecentArtifactType]
    RA_GITLAB_RELEASE: _ClassVar[RecentArtifactType]
    RA_BITBUCKET_REPO: _ClassVar[RecentArtifactType]
    RA_BITBUCKET_COMMIT: _ClassVar[RecentArtifactType]
    RA_BITBUCKET_PR: _ClassVar[RecentArtifactType]
UNKNOWN_F: Function
AVG_F: Function
SUM_F: Function
MIN_F: Function
MAX_F: Function
LAST_F: Function
UNKNOWN_O: Operator
GREATER_THAN_O: Operator
GREATER_THAN_EQUAL_O: Operator
LESS_THAN_O: Operator
LESS_THAN_EQUAL_O: Operator
EQUAL_O: Operator
NOT_EQUAL_O: Operator
LIKE_O: Operator
EXISTS_O: Operator
CONTAINS_O: Operator
UNKNOWN_LO: LogicalOperator
AND_LO: LogicalOperator
OR_LO: LogicalOperator
NOT_LO: LogicalOperator
UNKNOWN_OP: Op
EQ: Op
NEQ: Op
GT: Op
LT: Op
GTE: Op
LTE: Op
IN: Op
NOT_IN: Op
IS_NULL: Op
EXISTS: Op
AND: Op
OR: Op
NOT: Op
UNKNOWN: Source
SENTRY: Source
SEGMENT: Source
ELASTIC_SEARCH: Source
AMPLITUDE: Source
AWS_KINESIS: Source
CLOUDWATCH: Source
CLEVERTAP: Source
RUDDERSTACK: Source
MOENGAGE: Source
CRIBL: Source
KAFKA: Source
DATADOG: Source
FILEBEAT: Source
LOGSTASH: Source
FLUENTD: Source
FLUENTBIT: Source
PAGER_DUTY: Source
NEW_RELIC: Source
SLACK: Source
HONEYBADGER: Source
GOOGLE_CHAT: Source
DATADOG_OAUTH: Source
GCM: Source
PROMETHEUS: Source
ELASTIC_APM: Source
VICTORIA_METRICS: Source
SLACK_CONNECT: Source
GRAFANA: Source
CLICKHOUSE: Source
DOCUMENTATION: Source
POSTGRES: Source
OPS_GENIE: Source
EKS: Source
AGENT_PROXY: Source
GRAFANA_VPC: Source
GITHUB: Source
SQL_DATABASE_CONNECTION: Source
OPEN_AI: Source
REMOTE_SERVER: Source
API: Source
BASH: Source
AZURE: Source
GRAFANA_MIMIR: Source
GKE: Source
MS_TEAMS: Source
GRAFANA_LOKI: Source
KUBERNETES: Source
SMTP: Source
BIG_QUERY: Source
ZENDUTY: Source
ROOTLY: Source
JIRA_CLOUD: Source
ASANA: Source
CONFLUENCE_CLOUD: Source
CONFLUENCE_SELF_HOSTED: Source
GOOGLE_DRIVE: Source
NOTION: Source
DRD_PROXY_AGENT: Source
MONGODB: Source
OPEN_SEARCH: Source
LINEAR: Source
JENKINS: Source
GITHUB_ACTIONS: Source
CUSTOM_STRATEGIES: Source
ARGOCD: Source
DRD_ALERT_WEBHOOK: Source
ROLLBAR: Source
LAMBDA: Source
BROWSER: Source
POSTHOG: Source
MIXPANEL: Source
SIGNOZ: Source
BITBUCKET: Source
CORALOGIX: Source
RENDER: Source
MCP_SERVER: Source
VICTORIA_LOGS: Source
METABASE: Source
UNKNOWN_SKT: SourceKeyType
SENTRY_API_KEY: SourceKeyType
SENTRY_ORG_SLUG: SourceKeyType
DATADOG_APP_KEY: SourceKeyType
DATADOG_API_KEY: SourceKeyType
DATADOG_AUTH_TOKEN: SourceKeyType
DATADOG_API_DOMAIN: SourceKeyType
NEWRELIC_API_KEY: SourceKeyType
NEWRELIC_APP_ID: SourceKeyType
NEWRELIC_QUERY_KEY: SourceKeyType
NEWRELIC_API_DOMAIN: SourceKeyType
SLACK_BOT_AUTH_TOKEN: SourceKeyType
SLACK_CHANNEL_SKT: SourceKeyType
SLACK_APP_ID: SourceKeyType
SLACK_APP_CLIENT_ID: SourceKeyType
SLACK_APP_CLIENT_SECRET: SourceKeyType
SLACK_APP_SIGNING_SECRET: SourceKeyType
HONEYBADGER_USERNAME: SourceKeyType
HONEYBADGER_PASSWORD: SourceKeyType
HONEYBADGER_PROJECT_ID: SourceKeyType
AWS_ACCESS_KEY: SourceKeyType
AWS_SECRET_KEY: SourceKeyType
AWS_REGION: SourceKeyType
AWS_ASSUMED_ROLE_ARN: SourceKeyType
EKS_ROLE_ARN: SourceKeyType
AWS_DRD_CLOUD_ROLE_ARN: SourceKeyType
GOOGLE_CHAT_BOT_OAUTH_TOKEN: SourceKeyType
GOOGLE_CHAT_BOT_SPACES: SourceKeyType
GRAFANA_HOST: SourceKeyType
GRAFANA_API_KEY: SourceKeyType
GRAFANA_TEAM_HOST: SourceKeyType
CLICKHOUSE_INTERFACE: SourceKeyType
CLICKHOUSE_HOST: SourceKeyType
CLICKHOUSE_PORT: SourceKeyType
CLICKHOUSE_USER: SourceKeyType
CLICKHOUSE_PASSWORD: SourceKeyType
GCM_PROJECT_ID: SourceKeyType
GCM_PRIVATE_KEY: SourceKeyType
GCM_CLIENT_EMAIL: SourceKeyType
GCM_TOKEN_URI: SourceKeyType
GCM_SERVICE_ACCOUNT_JSON: SourceKeyType
POSTGRES_HOST: SourceKeyType
POSTGRES_USER: SourceKeyType
POSTGRES_PASSWORD: SourceKeyType
POSTGRES_PORT: SourceKeyType
POSTGRES_DATABASE: SourceKeyType
POSTGRES_OPTIONS: SourceKeyType
SQL_DATABASE_CONNECTION_STRING_URI: SourceKeyType
PAGER_DUTY_API_KEY: SourceKeyType
PAGER_DUTY_CONFIGURED_EMAIL: SourceKeyType
OPS_GENIE_API_KEY: SourceKeyType
AGENT_PROXY_HOST: SourceKeyType
AGENT_PROXY_API_KEY: SourceKeyType
GITHUB_TOKEN: SourceKeyType
GITHUB_ORG: SourceKeyType
OPEN_AI_API_KEY: SourceKeyType
REMOTE_SERVER_PEM: SourceKeyType
REMOTE_SERVER_USER: SourceKeyType
REMOTE_SERVER_HOST: SourceKeyType
REMOTE_SERVER_PASSWORD: SourceKeyType
REMOTE_SERVER_PORT: SourceKeyType
MIMIR_HOST: SourceKeyType
X_SCOPE_ORG_ID: SourceKeyType
SSL_VERIFY: SourceKeyType
AZURE_SUBSCRIPTION_ID: SourceKeyType
AZURE_TENANT_ID: SourceKeyType
AZURE_CLIENT_ID: SourceKeyType
AZURE_CLIENT_SECRET: SourceKeyType
GKE_PROJECT_ID: SourceKeyType
GKE_SERVICE_ACCOUNT_JSON: SourceKeyType
MS_TEAMS_CONNECTOR_WEBHOOK_URL: SourceKeyType
ELASTIC_SEARCH_PROTOCOL: SourceKeyType
ELASTIC_SEARCH_HOST: SourceKeyType
ELASTIC_SEARCH_PORT: SourceKeyType
ELASTIC_SEARCH_API_KEY_ID: SourceKeyType
ELASTIC_SEARCH_API_KEY: SourceKeyType
GRAFANA_LOKI_PROTOCOL: SourceKeyType
GRAFANA_LOKI_HOST: SourceKeyType
GRAFANA_LOKI_PORT: SourceKeyType
KUBERNETES_CLUSTER_NAME: SourceKeyType
KUBERNETES_CLUSTER_API_SERVER: SourceKeyType
KUBERNETES_CLUSTER_TOKEN: SourceKeyType
KUBERNETES_CLUSTER_CERTIFICATE_AUTHORITY_DATA: SourceKeyType
KUBERNETES_CLUSTER_CERTIFICATE_AUTHORITY_PATH: SourceKeyType
SMTP_HOST: SourceKeyType
SMTP_PORT: SourceKeyType
SMTP_USER: SourceKeyType
SMTP_PASSWORD: SourceKeyType
BIG_QUERY_PROJECT_ID: SourceKeyType
BIG_QUERY_SERVICE_ACCOUNT_JSON: SourceKeyType
ZENDUTY_API_KEY: SourceKeyType
ROOTLY_API_KEY: SourceKeyType
JIRA_CLOUD_API_KEY: SourceKeyType
JIRA_DOMAIN: SourceKeyType
JIRA_EMAIL: SourceKeyType
ASANA_ACCESS_TOKEN: SourceKeyType
CONFLUENCE_CLOUD_API_KEY: SourceKeyType
CONFLUENCE_CLOUD_SITE_URL: SourceKeyType
CONFLUENCE_CLOUD_ATLASSIAN_ACCOUNT_EMAIL: SourceKeyType
NOTION_API_KEY: SourceKeyType
DRD_PROXY_AGENT_HOST: SourceKeyType
DRD_PROXY_AGENT_API_TOKEN: SourceKeyType
DRD_PROXY_AGENT_API_KEY: SourceKeyType
MONGODB_CONNECTION_STRING: SourceKeyType
OPEN_SEARCH_PROTOCOL: SourceKeyType
OPEN_SEARCH_HOST: SourceKeyType
OPEN_SEARCH_PORT: SourceKeyType
OPEN_SEARCH_USERNAME: SourceKeyType
OPEN_SEARCH_PASSWORD: SourceKeyType
LINEAR_API_KEY: SourceKeyType
JENKINS_URL: SourceKeyType
JENKINS_USERNAME: SourceKeyType
JENKINS_API_TOKEN: SourceKeyType
JENKINS_CRUMB: SourceKeyType
GITHUB_ACTIONS_TOKEN: SourceKeyType
CUSTOM_STRATEGIES_ACCOUNT_ID: SourceKeyType
ARGOCD_SERVER: SourceKeyType
ARGOCD_TOKEN: SourceKeyType
ROLLBAR_ACCESS_TOKEN: SourceKeyType
POSTHOG_API_KEY: SourceKeyType
POSTHOG_APP_HOST: SourceKeyType
POSTHOG_PROJECT_ID: SourceKeyType
MIXPANEL_SERVICE_ACCOUNT_USERNAME: SourceKeyType
MIXPANEL_SERVICE_ACCOUNT_SECRET: SourceKeyType
MIXPANEL_DOMAIN: SourceKeyType
MIXPANEL_PROJECT_ID: SourceKeyType
MIXPANEL_WORKSPACE_ID: SourceKeyType
SIGNOZ_API_URL: SourceKeyType
SIGNOZ_API_TOKEN: SourceKeyType
KIBANA_HOST: SourceKeyType
BITBUCKET_WORKSPACE: SourceKeyType
BITBUCKET_API_KEY: SourceKeyType
BITBUCKET_REPO: SourceKeyType
RENDER_API_KEY: SourceKeyType
CORALOGIX_API_KEY: SourceKeyType
CORALOGIX_ENDPOINT: SourceKeyType
CORALOGIX_DOMAIN: SourceKeyType
MCP_SERVER_BASE_URL: SourceKeyType
MCP_SERVER_AUTH_HEADERS: SourceKeyType
VICTORIA_LOGS_PROTOCOL: SourceKeyType
VICTORIA_LOGS_HOST: SourceKeyType
VICTORIA_LOGS_PORT: SourceKeyType
VICTORIA_LOGS_HEADERS: SourceKeyType
GITHUB_APP_ID: SourceKeyType
GITHUB_APP_PRIVATE_KEY: SourceKeyType
GITHUB_APP_INSTALLATION_ID: SourceKeyType
GITHUB_APP_ACCESS_TOKEN: SourceKeyType
METABASE_URL: SourceKeyType
METABASE_API_KEY: SourceKeyType
UNKNOWN_MT: SourceModelType
NEW_RELIC_POLICY: SourceModelType
NEW_RELIC_CONDITION: SourceModelType
NEW_RELIC_ENTITY: SourceModelType
NEW_RELIC_ENTITY_DASHBOARD: SourceModelType
NEW_RELIC_ENTITY_APPLICATION: SourceModelType
NEW_RELIC_NRQL: SourceModelType
NEW_RELIC_ENTITY_DASHBOARD_V2: SourceModelType
DATADOG_MONITOR: SourceModelType
DATADOG_DASHBOARD: SourceModelType
DATADOG_LIVE_INTEGRATION_AWS: SourceModelType
DATADOG_LIVE_INTEGRATION_AWS_LOG: SourceModelType
DATADOG_LIVE_INTEGRATION_AZURE: SourceModelType
DATADOG_LIVE_INTEGRATION_CLOUDFLARE: SourceModelType
DATADOG_LIVE_INTEGRATION_FASTLY: SourceModelType
DATADOG_LIVE_INTEGRATION_GCP: SourceModelType
DATADOG_LIVE_INTEGRATION_CONFLUENT: SourceModelType
DATADOG_SERVICE: SourceModelType
DATADOG_METRIC: SourceModelType
DATADOG_QUERY: SourceModelType
DATADOG_APM: SourceModelType
DATADOG_FIELDS: SourceModelType
CLOUDWATCH_METRIC: SourceModelType
CLOUDWATCH_LOG_GROUP: SourceModelType
CLOUDWATCH_LOG_GROUP_QUERY: SourceModelType
CLOUDWATCH_ALARMS: SourceModelType
RDS_INSTANCES: SourceModelType
CLOUDWATCH_DASHBOARD: SourceModelType
GRAFANA_DATASOURCE: SourceModelType
GRAFANA_DASHBOARD: SourceModelType
GRAFANA_TARGET_METRIC_PROMQL: SourceModelType
GRAFANA_PROMETHEUS_DATASOURCE: SourceModelType
GRAFANA_ALERT_RULE: SourceModelType
GRAFANA_LOKI_DATASOURCE: SourceModelType
CLICKHOUSE_DATABASE: SourceModelType
CLICKHOUSE_TABLE: SourceModelType
SLACK_CHANNEL: SourceModelType
MARKDOWN: SourceModelType
IFRAME: SourceModelType
POSTGRES_QUERY: SourceModelType
POSTGRES_TABLE: SourceModelType
EKS_CLUSTER: SourceModelType
EKS_NAMESPACE: SourceModelType
EKS_SERVICE: SourceModelType
EKS_DEPLOYMENT: SourceModelType
EKS_INGRESS: SourceModelType
EKS_NETWORK_POLICY: SourceModelType
EKS_HPA: SourceModelType
EKS_REPLICASET: SourceModelType
EKS_STATEFULSET: SourceModelType
SQL_DATABASE_CONNECTION_RAW_QUERY: SourceModelType
SQL_DATABASE_TABLE: SourceModelType
AZURE_WORKSPACE: SourceModelType
AZURE_RESOURCE: SourceModelType
AZURE_AKS_CLUSTER: SourceModelType
AZURE_AKS_NAMESPACE: SourceModelType
AZURE_AKS_DEPLOYMENT: SourceModelType
AZURE_AKS_SERVICE: SourceModelType
AZURE_AKS_INGRESS: SourceModelType
AZURE_AKS_NETWORK_POLICY: SourceModelType
AZURE_AKS_HPA: SourceModelType
AZURE_AKS_REPLICASET: SourceModelType
AZURE_AKS_STATEFULSET: SourceModelType
AZURE_VIRTUAL_MACHINE: SourceModelType
AZURE_VMSS: SourceModelType
AZURE_STORAGE_ACCOUNT: SourceModelType
AZURE_BLOB_CONTAINER: SourceModelType
AZURE_SQL_SERVER: SourceModelType
AZURE_SQL_DATABASE: SourceModelType
AZURE_COSMOS_ACCOUNT: SourceModelType
AZURE_POSTGRES_SERVER: SourceModelType
AZURE_POSTGRES_DATABASE: SourceModelType
AZURE_METRIC_ALERT: SourceModelType
AZURE_ACTION_GROUP: SourceModelType
AZURE_RESOURCE_GROUP: SourceModelType
AZURE_REDIS_CACHE: SourceModelType
SSH_SERVER: SourceModelType
SSH_USER: SourceModelType
GRAFANA_MIMIR_PROMQL: SourceModelType
GKE_CLUSTER: SourceModelType
GKE_NAMESPACE: SourceModelType
GKE_SERVICE: SourceModelType
GKE_DEPLOYMENT: SourceModelType
GKE_INGRESS: SourceModelType
GKE_NETWORK_POLICY: SourceModelType
GKE_HPA: SourceModelType
GKE_REPLICASET: SourceModelType
GKE_STATEFULSET: SourceModelType
GCP_COMPUTE_INSTANCE: SourceModelType
GCP_INSTANCE_GROUP: SourceModelType
GCP_STORAGE_BUCKET: SourceModelType
GCP_CLOUD_SQL_INSTANCE: SourceModelType
GCP_CLOUD_SQL_DATABASE: SourceModelType
GCP_MEMORYSTORE_REDIS: SourceModelType
GCP_ALERT_POLICY: SourceModelType
GCP_NOTIFICATION_CHANNEL: SourceModelType
GCP_CLOUD_FUNCTION: SourceModelType
GCP_CLOUD_RUN_SERVICE: SourceModelType
GCP_PUBSUB_TOPIC: SourceModelType
GCP_PUBSUB_SUBSCRIPTION: SourceModelType
GCP_BIGQUERY_DATASET: SourceModelType
GCP_BIGQUERY_TABLE: SourceModelType
GCP_VPC_NETWORK: SourceModelType
GCP_SUBNETWORK: SourceModelType
GCP_FIREWALL_RULE: SourceModelType
GCP_LOAD_BALANCER: SourceModelType
GCP_SECRET: SourceModelType
GCP_SERVICE_ACCOUNT: SourceModelType
GCP_LOG_SINK: SourceModelType
GCP_LOG_METRIC: SourceModelType
MS_TEAMS_CHANNEL: SourceModelType
PAGERDUTY_INCIDENT: SourceModelType
ELASTIC_SEARCH_INDEX: SourceModelType
ELASTIC_SEARCH_SERVICES: SourceModelType
ELASTIC_SEARCH_DASHBOARDS: SourceModelType
ELASTIC_SEARCH_INDEX_PATTERNS: SourceModelType
GCM_METRIC: SourceModelType
GCM_DASHBOARD: SourceModelType
GCM_CLOUD_RUN_SERVICE_DASHBOARD: SourceModelType
ZENDUTY_INCIDENT: SourceModelType
ROOTLY_INCIDENT: SourceModelType
OPS_GENIE_ESCALATION: SourceModelType
OPS_GENIE_TEAM: SourceModelType
GOOGLE_CHAT_SPACE: SourceModelType
MONGODB_DATABASE: SourceModelType
MONGODB_COLLECTION: SourceModelType
OPEN_SEARCH_INDEX: SourceModelType
ASANA_PROJECT: SourceModelType
MODELS_ACTIVE: SourceModelType
GITHUB_REPOSITORY: SourceModelType
GITHUB_MEMBER: SourceModelType
JIRA_PROJECT: SourceModelType
JIRA_USER: SourceModelType
ARGOCD_APPS: SourceModelType
JENKINS_JOBS: SourceModelType
POSTHOG_PERSON: SourceModelType
POSTHOG_GROUP: SourceModelType
POSTHOG_COHORT: SourceModelType
POSTHOG_PROPERTY: SourceModelType
ECS_CLUSTER: SourceModelType
ECS_TASK: SourceModelType
ECS_SERVICE: SourceModelType
SIGNOZ_DASHBOARD: SourceModelType
SIGNOZ_ALERT: SourceModelType
SIGNOZ_METRIC: SourceModelType
SIGNOZ_SERVICE: SourceModelType
SIGNOZ_LOG_ATTRIBUTES: SourceModelType
KUBERNETES_NAMESPACE: SourceModelType
KUBERNETES_SERVICE: SourceModelType
KUBERNETES_DEPLOYMENT: SourceModelType
KUBERNETES_INGRESS: SourceModelType
KUBERNETES_NETWORK_POLICY: SourceModelType
KUBERNETES_HPA: SourceModelType
KUBERNETES_REPLICASET: SourceModelType
KUBERNETES_STATEFULSET: SourceModelType
KUBERNETES_NETWORK_MAP: SourceModelType
SENTRY_PROJECT: SourceModelType
CORALOGIX_DASHBOARD: SourceModelType
CORALOGIX_INDEX_MAPPING: SourceModelType
VICTORIA_LOGS_FIELD: SourceModelType
MCP_TOOLS: SourceModelType
UNKNOWN_C: Context
EVENT: Context
MONITOR_TRANSACTION: Context
ENTITY_INSTANCE: Context
EVENT_TYPE: Context
MONITOR: Context
ENTITY: Context
EVENTS_CLICKHOUSE: Context
PANEL_NAME: Context
DASHBOARD_NAME: Context
EVENTS_ALERT_OPS_CLICKHOUSE: Context
SLACK_ALERT: Context
EVENTS_PRODIGAL_CLICKHOUSE: Context
ALERT_OPS: Context
ALERT_MIDDLEWARE: Context
RA_UNKNOWN: RecentArtifactType
RA_GITHUB_REPO: RecentArtifactType
RA_GITHUB_COMMIT: RecentArtifactType
RA_GITHUB_PR: RecentArtifactType
RA_GITHUB_RELEASE: RecentArtifactType
RA_GITLAB_REPO: RecentArtifactType
RA_GITLAB_COMMIT: RecentArtifactType
RA_GITLAB_MR: RecentArtifactType
RA_GITLAB_RELEASE: RecentArtifactType
RA_BITBUCKET_REPO: RecentArtifactType
RA_BITBUCKET_COMMIT: RecentArtifactType
RA_BITBUCKET_PR: RecentArtifactType

class TimeRange(_message.Message):
    __slots__ = ("time_geq", "time_lt")
    TIME_GEQ_FIELD_NUMBER: _ClassVar[int]
    TIME_LT_FIELD_NUMBER: _ClassVar[int]
    time_geq: int
    time_lt: int
    def __init__(self, time_geq: _Optional[int] = ..., time_lt: _Optional[int] = ...) -> None: ...

class Page(_message.Message):
    __slots__ = ("limit", "offset")
    LIMIT_FIELD_NUMBER: _ClassVar[int]
    OFFSET_FIELD_NUMBER: _ClassVar[int]
    limit: _wrappers_pb2.UInt32Value
    offset: _wrappers_pb2.UInt32Value
    def __init__(self, limit: _Optional[_Union[_wrappers_pb2.UInt32Value, _Mapping]] = ..., offset: _Optional[_Union[_wrappers_pb2.UInt32Value, _Mapping]] = ...) -> None: ...

class OpDescription(_message.Message):
    __slots__ = ("op", "label", "is_unary", "is_logical")
    OP_FIELD_NUMBER: _ClassVar[int]
    LABEL_FIELD_NUMBER: _ClassVar[int]
    IS_UNARY_FIELD_NUMBER: _ClassVar[int]
    IS_LOGICAL_FIELD_NUMBER: _ClassVar[int]
    op: Op
    label: str
    is_unary: bool
    is_logical: bool
    def __init__(self, op: _Optional[_Union[Op, str]] = ..., label: _Optional[str] = ..., is_unary: bool = ..., is_logical: bool = ...) -> None: ...

class TaskCronSchedule(_message.Message):
    __slots__ = ("minutes", "hours", "days_of_the_week", "days_of_the_month", "days_of_the_year", "timezone")
    MINUTES_FIELD_NUMBER: _ClassVar[int]
    HOURS_FIELD_NUMBER: _ClassVar[int]
    DAYS_OF_THE_WEEK_FIELD_NUMBER: _ClassVar[int]
    DAYS_OF_THE_MONTH_FIELD_NUMBER: _ClassVar[int]
    DAYS_OF_THE_YEAR_FIELD_NUMBER: _ClassVar[int]
    TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    minutes: _wrappers_pb2.StringValue
    hours: _wrappers_pb2.StringValue
    days_of_the_week: _wrappers_pb2.StringValue
    days_of_the_month: _wrappers_pb2.StringValue
    days_of_the_year: _wrappers_pb2.StringValue
    timezone: _wrappers_pb2.StringValue
    def __init__(self, minutes: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., hours: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., days_of_the_week: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., days_of_the_month: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., days_of_the_year: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., timezone: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ...) -> None: ...

class TaskInterval(_message.Message):
    __slots__ = ("interval_in_seconds",)
    INTERVAL_IN_SECONDS_FIELD_NUMBER: _ClassVar[int]
    interval_in_seconds: _wrappers_pb2.UInt64Value
    def __init__(self, interval_in_seconds: _Optional[_Union[_wrappers_pb2.UInt64Value, _Mapping]] = ...) -> None: ...

class TaskCronRule(_message.Message):
    __slots__ = ("rule", "timezone")
    RULE_FIELD_NUMBER: _ClassVar[int]
    TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    rule: _wrappers_pb2.StringValue
    timezone: _wrappers_pb2.StringValue
    def __init__(self, rule: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., timezone: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ...) -> None: ...

class EventKey(_message.Message):
    __slots__ = ("id", "key", "key_type", "event_type")
    class KeyType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        UNKNOWN: _ClassVar[EventKey.KeyType]
        STRING: _ClassVar[EventKey.KeyType]
        LONG: _ClassVar[EventKey.KeyType]
        DOUBLE: _ClassVar[EventKey.KeyType]
        BOOLEAN: _ClassVar[EventKey.KeyType]
        BYTE: _ClassVar[EventKey.KeyType]
        ARRAY: _ClassVar[EventKey.KeyType]
        OBJECT: _ClassVar[EventKey.KeyType]
    UNKNOWN: EventKey.KeyType
    STRING: EventKey.KeyType
    LONG: EventKey.KeyType
    DOUBLE: EventKey.KeyType
    BOOLEAN: EventKey.KeyType
    BYTE: EventKey.KeyType
    ARRAY: EventKey.KeyType
    OBJECT: EventKey.KeyType
    ID_FIELD_NUMBER: _ClassVar[int]
    KEY_FIELD_NUMBER: _ClassVar[int]
    KEY_TYPE_FIELD_NUMBER: _ClassVar[int]
    EVENT_TYPE_FIELD_NUMBER: _ClassVar[int]
    id: int
    key: str
    key_type: EventKey.KeyType
    event_type: EventTypePartial
    def __init__(self, id: _Optional[int] = ..., key: _Optional[str] = ..., key_type: _Optional[_Union[EventKey.KeyType, str]] = ..., event_type: _Optional[_Union[EventTypePartial, _Mapping]] = ...) -> None: ...

class EventType(_message.Message):
    __slots__ = ("id", "name", "keys", "event_sources")
    ID_FIELD_NUMBER: _ClassVar[int]
    NAME_FIELD_NUMBER: _ClassVar[int]
    KEYS_FIELD_NUMBER: _ClassVar[int]
    EVENT_SOURCES_FIELD_NUMBER: _ClassVar[int]
    id: int
    name: str
    keys: _containers.RepeatedCompositeFieldContainer[EventKey]
    event_sources: _containers.RepeatedScalarFieldContainer[Event.EventSource]
    def __init__(self, id: _Optional[int] = ..., name: _Optional[str] = ..., keys: _Optional[_Iterable[_Union[EventKey, _Mapping]]] = ..., event_sources: _Optional[_Iterable[_Union[Event.EventSource, str]]] = ...) -> None: ...

class EventTypeStats(_message.Message):
    __slots__ = ("keys_count", "event_count", "monitor_count")
    KEYS_COUNT_FIELD_NUMBER: _ClassVar[int]
    EVENT_COUNT_FIELD_NUMBER: _ClassVar[int]
    MONITOR_COUNT_FIELD_NUMBER: _ClassVar[int]
    keys_count: _wrappers_pb2.UInt64Value
    event_count: _wrappers_pb2.UInt64Value
    monitor_count: _wrappers_pb2.UInt64Value
    def __init__(self, keys_count: _Optional[_Union[_wrappers_pb2.UInt64Value, _Mapping]] = ..., event_count: _Optional[_Union[_wrappers_pb2.UInt64Value, _Mapping]] = ..., monitor_count: _Optional[_Union[_wrappers_pb2.UInt64Value, _Mapping]] = ...) -> None: ...

class EventTypePartial(_message.Message):
    __slots__ = ("id", "name")
    ID_FIELD_NUMBER: _ClassVar[int]
    NAME_FIELD_NUMBER: _ClassVar[int]
    id: int
    name: str
    def __init__(self, id: _Optional[int] = ..., name: _Optional[str] = ...) -> None: ...

class EventTypeSummary(_message.Message):
    __slots__ = ("event_type", "stats")
    EVENT_TYPE_FIELD_NUMBER: _ClassVar[int]
    STATS_FIELD_NUMBER: _ClassVar[int]
    event_type: EventTypePartial
    stats: EventTypeStats
    def __init__(self, event_type: _Optional[_Union[EventTypePartial, _Mapping]] = ..., stats: _Optional[_Union[EventTypeStats, _Mapping]] = ...) -> None: ...

class EventTypeDefinition(_message.Message):
    __slots__ = ("event_type", "stats")
    EVENT_TYPE_FIELD_NUMBER: _ClassVar[int]
    STATS_FIELD_NUMBER: _ClassVar[int]
    event_type: EventType
    stats: EventTypeStats
    def __init__(self, event_type: _Optional[_Union[EventType, _Mapping]] = ..., stats: _Optional[_Union[EventTypeStats, _Mapping]] = ...) -> None: ...

class Event(_message.Message):
    __slots__ = ("id", "event_type", "kvs", "timestamp", "event_source")
    class EventSource(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        UNKNOWN: _ClassVar[Event.EventSource]
        SAMPLE: _ClassVar[Event.EventSource]
        API: _ClassVar[Event.EventSource]
        SDK: _ClassVar[Event.EventSource]
        SEGMENT: _ClassVar[Event.EventSource]
        AMPLITUDE: _ClassVar[Event.EventSource]
        SNS: _ClassVar[Event.EventSource]
        CLOUDWATCH: _ClassVar[Event.EventSource]
        COLLECTOR: _ClassVar[Event.EventSource]
        AWS_KINESIS: _ClassVar[Event.EventSource]
        SLACK: _ClassVar[Event.EventSource]
        OPS_GENIE: _ClassVar[Event.EventSource]
    UNKNOWN: Event.EventSource
    SAMPLE: Event.EventSource
    API: Event.EventSource
    SDK: Event.EventSource
    SEGMENT: Event.EventSource
    AMPLITUDE: Event.EventSource
    SNS: Event.EventSource
    CLOUDWATCH: Event.EventSource
    COLLECTOR: Event.EventSource
    AWS_KINESIS: Event.EventSource
    SLACK: Event.EventSource
    OPS_GENIE: Event.EventSource
    ID_FIELD_NUMBER: _ClassVar[int]
    EVENT_TYPE_FIELD_NUMBER: _ClassVar[int]
    KVS_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    EVENT_SOURCE_FIELD_NUMBER: _ClassVar[int]
    id: int
    event_type: EventTypePartial
    kvs: _containers.RepeatedCompositeFieldContainer[KeyValue]
    timestamp: int
    event_source: Event.EventSource
    def __init__(self, id: _Optional[int] = ..., event_type: _Optional[_Union[EventTypePartial, _Mapping]] = ..., kvs: _Optional[_Iterable[_Union[KeyValue, _Mapping]]] = ..., timestamp: _Optional[int] = ..., event_source: _Optional[_Union[Event.EventSource, str]] = ...) -> None: ...

class Value(_message.Message):
    __slots__ = ("string_value", "bool_value", "int_value", "double_value", "array_value", "kvlist_value", "bytes_value")
    STRING_VALUE_FIELD_NUMBER: _ClassVar[int]
    BOOL_VALUE_FIELD_NUMBER: _ClassVar[int]
    INT_VALUE_FIELD_NUMBER: _ClassVar[int]
    DOUBLE_VALUE_FIELD_NUMBER: _ClassVar[int]
    ARRAY_VALUE_FIELD_NUMBER: _ClassVar[int]
    KVLIST_VALUE_FIELD_NUMBER: _ClassVar[int]
    BYTES_VALUE_FIELD_NUMBER: _ClassVar[int]
    string_value: str
    bool_value: bool
    int_value: int
    double_value: float
    array_value: ArrayValue
    kvlist_value: KeyValueList
    bytes_value: bytes
    def __init__(self, string_value: _Optional[str] = ..., bool_value: bool = ..., int_value: _Optional[int] = ..., double_value: _Optional[float] = ..., array_value: _Optional[_Union[ArrayValue, _Mapping]] = ..., kvlist_value: _Optional[_Union[KeyValueList, _Mapping]] = ..., bytes_value: _Optional[bytes] = ...) -> None: ...

class ArrayValue(_message.Message):
    __slots__ = ("values",)
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedCompositeFieldContainer[Value]
    def __init__(self, values: _Optional[_Iterable[_Union[Value, _Mapping]]] = ...) -> None: ...

class KeyValueList(_message.Message):
    __slots__ = ("values",)
    VALUES_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedCompositeFieldContainer[KeyValue]
    def __init__(self, values: _Optional[_Iterable[_Union[KeyValue, _Mapping]]] = ...) -> None: ...

class KeyValue(_message.Message):
    __slots__ = ("key", "value")
    KEY_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    key: str
    value: Value
    def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[Value, _Mapping]] = ...) -> None: ...
