# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/protos/agent_logs/agent_logs_commons.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'core/protos/agent_logs/agent_logs_commons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/core/protos/agent_logs/agent_logs_commons.proto\x12\x16\x63ore.protos.agent_logs\x1a\x1egoogle/protobuf/wrappers.proto\"\xa3\x01\n\x08\x41gentLog\x12-\n\x07message\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12\x36\n\x10session_sequence\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt64Valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.agent_logs.agent_logs_commons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTLOG']._serialized_start=108
  _globals['_AGENTLOG']._serialized_end=271
# @@protoc_insertion_point(module_scope)
