# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/protos/agent_logs/api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.protos.connectors import api_pb2 as core_dot_protos_dot_connectors_dot_api__pb2
from core.protos.agent_logs import agent_logs_commons_pb2 as core_dot_protos_dot_agent__logs_dot_agent__logs__commons__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n core/protos/agent_logs/api.proto\x12\x16\x63ore.protos.agent_logs\x1a core/protos/connectors/api.proto\x1a/core/protos/agent_logs/agent_logs_commons.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xcb\x01\n\"ApiInvestigationAddAgentLogRequest\x12>\n\x18investigation_session_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07message\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x36\n\x10session_sequence\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\"\x84\x01\n#ApiInvestigationAddAgentLogResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x07message\x18\x02 \x01(\x0b\x32\x1f.core.protos.connectors.Message\"\xbd\x01\n\x12GetAgentLogRequest\x12>\n\x18investigation_session_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nsession_id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x0flast_created_at\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\"\xa4\x01\n\x13GetAgentLogResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x07message\x18\x02 \x01(\x0b\x32\x1f.core.protos.connectors.Message\x12.\n\x04logs\x18\x03 \x03(\x0b\x32 .core.protos.agent_logs.AgentLogb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.agent_logs.api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APIINVESTIGATIONADDAGENTLOGREQUEST._serialized_start=176
  _APIINVESTIGATIONADDAGENTLOGREQUEST._serialized_end=379
  _APIINVESTIGATIONADDAGENTLOGRESPONSE._serialized_start=382
  _APIINVESTIGATIONADDAGENTLOGRESPONSE._serialized_end=514
  _GETAGENTLOGREQUEST._serialized_start=517
  _GETAGENTLOGREQUEST._serialized_end=706
  _GETAGENTLOGRESPONSE._serialized_start=709
  _GETAGENTLOGRESPONSE._serialized_end=873
# @@protoc_insertion_point(module_scope)
