"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EventType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN_ET: _EventType.ValueType  # 0
    OAUTH_CALLBACK: _EventType.ValueType  # 1
    EVENT_CALLBACK: _EventType.ValueType  # 2

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...

UNKNOWN_ET: EventType.ValueType  # 0
OAUTH_CALLBACK: EventType.ValueType  # 1
EVENT_CALLBACK: EventType.ValueType  # 2
global___EventType = EventType
