"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.base_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ArgoCDAppsAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPS_FIELD_NUMBER: builtins.int
    @property
    def apps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Names of apps, calling it apps to maintain code uniformity"""

    def __init__(
        self,
        *,
        apps: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["apps", b"apps"]) -> None: ...

global___ArgoCDAppsAssetOptions = ArgoCDAppsAssetOptions

@typing.final
class ArgoCDAppsAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def path(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        path: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["name", b"name", "path", b"path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "path", b"path"]) -> None: ...

global___ArgoCDAppsAssetModel = ArgoCDAppsAssetModel

@typing.final
class ArgoCDAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    ARGOCD_APPS_FIELD_NUMBER: builtins.int
    connector_type: core.protos.base_pb2.Source.ValueType
    type: core.protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def argocd_apps(self) -> global___ArgoCDAppsAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: core.protos.base_pb2.Source.ValueType = ...,
        type: core.protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        argocd_apps: global___ArgoCDAppsAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["argocd_apps", b"argocd_apps", "asset", b"asset", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["argocd_apps", b"argocd_apps", "asset", b"asset", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["asset", b"asset"]) -> typing.Literal["argocd_apps"] | None: ...

global___ArgoCDAssetModel = ArgoCDAssetModel

@typing.final
class ArgoCDAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ArgoCDAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___ArgoCDAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["assets", b"assets"]) -> None: ...

global___ArgoCDAssets = ArgoCDAssets
