"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import core.protos.base_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BitbucketRepositoryAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SLUG_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FULL_NAME_FIELD_NUMBER: builtins.int
    HTML_URL_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    IS_PRIVATE_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    @property
    def slug(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def full_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def html_url(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def is_private(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def owner(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        slug: google.protobuf.wrappers_pb2.StringValue | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        full_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        html_url: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        is_private: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        owner: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["description", b"description", "full_name", b"full_name", "html_url", b"html_url", "is_private", b"is_private", "name", b"name", "owner", b"owner", "slug", b"slug"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "full_name", b"full_name", "html_url", b"html_url", "is_private", b"is_private", "name", b"name", "owner", b"owner", "slug", b"slug"]) -> None: ...

global___BitbucketRepositoryAssetModel = BitbucketRepositoryAssetModel

@typing_extensions.final
class BitbucketWorkspaceMemberAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    NICKNAME_FIELD_NUMBER: builtins.int
    @property
    def display_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def uuid(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def nickname(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        display_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        uuid: google.protobuf.wrappers_pb2.StringValue | None = ...,
        nickname: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["display_name", b"display_name", "nickname", b"nickname", "uuid", b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["display_name", b"display_name", "nickname", b"nickname", "uuid", b"uuid"]) -> None: ...

global___BitbucketWorkspaceMemberAssetModel = BitbucketWorkspaceMemberAssetModel

@typing_extensions.final
class BitbucketRepositoryAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class BitbucketRepository(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SLUG_FIELD_NUMBER: builtins.int
        @property
        def slug(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            slug: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["slug", b"slug"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["slug", b"slug"]) -> None: ...

    REPOSITORIES_FIELD_NUMBER: builtins.int
    @property
    def repositories(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BitbucketRepositoryAssetOptions.BitbucketRepository]: ...
    def __init__(
        self,
        *,
        repositories: collections.abc.Iterable[global___BitbucketRepositoryAssetOptions.BitbucketRepository] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["repositories", b"repositories"]) -> None: ...

global___BitbucketRepositoryAssetOptions = BitbucketRepositoryAssetOptions

@typing_extensions.final
class BitbucketWorkspaceMemberAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class BitbucketWorkspaceMember(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DISPLAY_NAME_FIELD_NUMBER: builtins.int
        @property
        def display_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            display_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["display_name", b"display_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["display_name", b"display_name"]) -> None: ...

    MEMBERS_FIELD_NUMBER: builtins.int
    @property
    def members(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BitbucketWorkspaceMemberAssetOptions.BitbucketWorkspaceMember]: ...
    def __init__(
        self,
        *,
        members: collections.abc.Iterable[global___BitbucketWorkspaceMemberAssetOptions.BitbucketWorkspaceMember] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["members", b"members"]) -> None: ...

global___BitbucketWorkspaceMemberAssetOptions = BitbucketWorkspaceMemberAssetOptions

@typing_extensions.final
class BitbucketAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    BITBUCKET_REPOSITORY_FIELD_NUMBER: builtins.int
    BITBUCKET_WORKSPACE_MEMBER_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: core.protos.base_pb2.Source.ValueType
    type: core.protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def bitbucket_repository(self) -> global___BitbucketRepositoryAssetModel: ...
    @property
    def bitbucket_workspace_member(self) -> global___BitbucketWorkspaceMemberAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: core.protos.base_pb2.Source.ValueType = ...,
        type: core.protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        bitbucket_repository: global___BitbucketRepositoryAssetModel | None = ...,
        bitbucket_workspace_member: global___BitbucketWorkspaceMemberAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "bitbucket_repository", b"bitbucket_repository", "bitbucket_workspace_member", b"bitbucket_workspace_member", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "bitbucket_repository", b"bitbucket_repository", "bitbucket_workspace_member", b"bitbucket_workspace_member", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["bitbucket_repository", "bitbucket_workspace_member"] | None: ...

global___BitbucketAssetModel = BitbucketAssetModel

@typing_extensions.final
class BitbucketAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BitbucketAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___BitbucketAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___BitbucketAssets = BitbucketAssets
