"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.base_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ClickhouseDatabaseAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATABASE_FIELD_NUMBER: builtins.int
    @property
    def database(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        database: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["database", b"database"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["database", b"database"]) -> None: ...

Global___ClickhouseDatabaseAssetModel: typing_extensions.TypeAlias = ClickhouseDatabaseAssetModel

@typing.final
class ClickhouseDatabaseAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATABASES_FIELD_NUMBER: builtins.int
    @property
    def databases(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        databases: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["databases", b"databases"]) -> None: ...

Global___ClickhouseDatabaseAssetOptions: typing_extensions.TypeAlias = ClickhouseDatabaseAssetOptions

@typing.final
class ClickhouseColumnModel(google.protobuf.message.Message):
    """Column model for tables"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    IS_NULLABLE_FIELD_NUMBER: builtins.int
    DEFAULT_VALUE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def data_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def is_nullable(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def default_value(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        data_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
        is_nullable: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        default_value: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data_type", b"data_type", "default_value", b"default_value", "description", b"description", "is_nullable", b"is_nullable", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data_type", b"data_type", "default_value", b"default_value", "description", b"description", "is_nullable", b"is_nullable", "name", b"name"]) -> None: ...

Global___ClickhouseColumnModel: typing_extensions.TypeAlias = ClickhouseColumnModel

@typing.final
class ClickhouseTableAssetModel(google.protobuf.message.Message):
    """Table asset"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TABLE_NAME_FIELD_NUMBER: builtins.int
    DATABASE_NAME_FIELD_NUMBER: builtins.int
    ENGINE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    COLUMNS_FIELD_NUMBER: builtins.int
    @property
    def table_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def database_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def engine(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def size(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def columns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ClickhouseColumnModel]: ...
    def __init__(
        self,
        *,
        table_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        database_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        engine: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        size: google.protobuf.wrappers_pb2.StringValue | None = ...,
        columns: collections.abc.Iterable[Global___ClickhouseColumnModel] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["database_name", b"database_name", "description", b"description", "engine", b"engine", "size", b"size", "table_name", b"table_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["columns", b"columns", "database_name", b"database_name", "description", b"description", "engine", b"engine", "size", b"size", "table_name", b"table_name"]) -> None: ...

Global___ClickhouseTableAssetModel: typing_extensions.TypeAlias = ClickhouseTableAssetModel

@typing.final
class ClickhouseTableAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TABLES_FIELD_NUMBER: builtins.int
    DATABASES_FIELD_NUMBER: builtins.int
    @property
    def tables(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def databases(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        tables: collections.abc.Iterable[builtins.str] | None = ...,
        databases: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["databases", b"databases", "tables", b"tables"]) -> None: ...

Global___ClickhouseTableAssetOptions: typing_extensions.TypeAlias = ClickhouseTableAssetOptions

@typing.final
class ClickhouseAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    CLICKHOUSE_DATABASE_FIELD_NUMBER: builtins.int
    CLICKHOUSE_TABLE_FIELD_NUMBER: builtins.int
    connector_type: core.protos.base_pb2.Source.ValueType
    type: core.protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def clickhouse_database(self) -> Global___ClickhouseDatabaseAssetModel: ...
    @property
    def clickhouse_table(self) -> Global___ClickhouseTableAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: core.protos.base_pb2.Source.ValueType = ...,
        type: core.protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        clickhouse_database: Global___ClickhouseDatabaseAssetModel | None = ...,
        clickhouse_table: Global___ClickhouseTableAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["asset", b"asset", "clickhouse_database", b"clickhouse_database", "clickhouse_table", b"clickhouse_table", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["asset", b"asset", "clickhouse_database", b"clickhouse_database", "clickhouse_table", b"clickhouse_table", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["asset", b"asset"]) -> typing.Literal["clickhouse_database", "clickhouse_table"] | None: ...

Global___ClickhouseAssetModel: typing_extensions.TypeAlias = ClickhouseAssetModel

@typing.final
class ClickhouseAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ClickhouseAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[Global___ClickhouseAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["assets", b"assets"]) -> None: ...

Global___ClickhouseAssets: typing_extensions.TypeAlias = ClickhouseAssets
