"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import core.protos.base_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.wrappers_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CoralogixDashboardWidgetAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Widget(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        WIDGET_ID_FIELD_NUMBER: builtins.int
        WIDGET_TYPE_FIELD_NUMBER: builtins.int
        WIDGET_TITLE_FIELD_NUMBER: builtins.int
        WIDGET_QUERY_FIELD_NUMBER: builtins.int
        WIDGET_CONFIG_FIELD_NUMBER: builtins.int
        WIDGET_JSON_FIELD_NUMBER: builtins.int
        @property
        def widget_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_config(self) -> google.protobuf.struct_pb2.Struct: ...
        @property
        def widget_json(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            widget_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_title: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_query: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_config: google.protobuf.struct_pb2.Struct | None = ...,
            widget_json: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["widget_config", b"widget_config", "widget_id", b"widget_id", "widget_json", b"widget_json", "widget_query", b"widget_query", "widget_title", b"widget_title", "widget_type", b"widget_type"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["widget_config", b"widget_config", "widget_id", b"widget_id", "widget_json", b"widget_json", "widget_query", b"widget_query", "widget_title", b"widget_title", "widget_type", b"widget_type"]) -> None: ...

    DASHBOARD_ID_FIELD_NUMBER: builtins.int
    DASHBOARD_TITLE_FIELD_NUMBER: builtins.int
    DASHBOARD_JSON_FIELD_NUMBER: builtins.int
    WIDGETS_FIELD_NUMBER: builtins.int
    @property
    def dashboard_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def dashboard_title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def dashboard_json(self) -> google.protobuf.struct_pb2.Struct: ...
    @property
    def widgets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CoralogixDashboardWidgetAssetModel.Widget]: ...
    def __init__(
        self,
        *,
        dashboard_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        dashboard_title: google.protobuf.wrappers_pb2.StringValue | None = ...,
        dashboard_json: google.protobuf.struct_pb2.Struct | None = ...,
        widgets: collections.abc.Iterable[global___CoralogixDashboardWidgetAssetModel.Widget] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dashboard_id", b"dashboard_id", "dashboard_json", b"dashboard_json", "dashboard_title", b"dashboard_title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dashboard_id", b"dashboard_id", "dashboard_json", b"dashboard_json", "dashboard_title", b"dashboard_title", "widgets", b"widgets"]) -> None: ...

global___CoralogixDashboardWidgetAssetModel = CoralogixDashboardWidgetAssetModel

@typing_extensions.final
class CoralogixDashboardAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class CoralogixDashboardOptions(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DASHBOARD_ID_FIELD_NUMBER: builtins.int
        DASHBOARD_TITLE_FIELD_NUMBER: builtins.int
        @property
        def dashboard_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def dashboard_title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            dashboard_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            dashboard_title: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["dashboard_id", b"dashboard_id", "dashboard_title", b"dashboard_title"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["dashboard_id", b"dashboard_id", "dashboard_title", b"dashboard_title"]) -> None: ...

    DASHBOARDS_FIELD_NUMBER: builtins.int
    @property
    def dashboards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CoralogixDashboardAssetOptions.CoralogixDashboardOptions]: ...
    def __init__(
        self,
        *,
        dashboards: collections.abc.Iterable[global___CoralogixDashboardAssetOptions.CoralogixDashboardOptions] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dashboards", b"dashboards"]) -> None: ...

global___CoralogixDashboardAssetOptions = CoralogixDashboardAssetOptions

@typing_extensions.final
class CoralogixServiceAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_NAME_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    SUBSYSTEM_NAME_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def service_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def environment(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def subsystem_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def application_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        service_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        environment: google.protobuf.wrappers_pb2.StringValue | None = ...,
        subsystem_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        application_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["application_name", b"application_name", "description", b"description", "environment", b"environment", "service_name", b"service_name", "subsystem_name", b"subsystem_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["application_name", b"application_name", "description", b"description", "environment", b"environment", "service_name", b"service_name", "subsystem_name", b"subsystem_name"]) -> None: ...

global___CoralogixServiceAssetModel = CoralogixServiceAssetModel

@typing_extensions.final
class CoralogixServiceAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class CoralogixServiceOptions(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SERVICE_NAME_FIELD_NUMBER: builtins.int
        @property
        def service_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            service_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["service_name", b"service_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["service_name", b"service_name"]) -> None: ...

    SERVICES_FIELD_NUMBER: builtins.int
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CoralogixServiceAssetOptions.CoralogixServiceOptions]: ...
    def __init__(
        self,
        *,
        services: collections.abc.Iterable[global___CoralogixServiceAssetOptions.CoralogixServiceOptions] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["services", b"services"]) -> None: ...

global___CoralogixServiceAssetOptions = CoralogixServiceAssetOptions

@typing_extensions.final
class CoralogixAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    CORALOGIX_DASHBOARD_FIELD_NUMBER: builtins.int
    CORALOGIX_INDEX_MAPPING_FIELD_NUMBER: builtins.int
    CORALOGIX_SERVICE_FIELD_NUMBER: builtins.int
    CORALOGIX_APM_SERVICE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: core.protos.base_pb2.Source.ValueType
    type: core.protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def coralogix_dashboard(self) -> global___CoralogixDashboardWidgetAssetModel: ...
    @property
    def coralogix_index_mapping(self) -> global___CoralogixIndexMappingAssetModel: ...
    @property
    def coralogix_service(self) -> global___CoralogixServiceAssetModel: ...
    @property
    def coralogix_apm_service(self) -> global___CoralogixApmServiceAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: core.protos.base_pb2.Source.ValueType = ...,
        type: core.protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        coralogix_dashboard: global___CoralogixDashboardWidgetAssetModel | None = ...,
        coralogix_index_mapping: global___CoralogixIndexMappingAssetModel | None = ...,
        coralogix_service: global___CoralogixServiceAssetModel | None = ...,
        coralogix_apm_service: global___CoralogixApmServiceAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "coralogix_apm_service", b"coralogix_apm_service", "coralogix_dashboard", b"coralogix_dashboard", "coralogix_index_mapping", b"coralogix_index_mapping", "coralogix_service", b"coralogix_service", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "connector_type", b"connector_type", "coralogix_apm_service", b"coralogix_apm_service", "coralogix_dashboard", b"coralogix_dashboard", "coralogix_index_mapping", b"coralogix_index_mapping", "coralogix_service", b"coralogix_service", "id", b"id", "last_updated", b"last_updated", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["coralogix_dashboard", "coralogix_index_mapping", "coralogix_service", "coralogix_apm_service"] | None: ...

global___CoralogixAssetModel = CoralogixAssetModel

@typing_extensions.final
class CoralogixIndexMappingAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_NAME_FIELD_NUMBER: builtins.int
    INDEX_PATTERN_FIELD_NUMBER: builtins.int
    MAPPING_DATA_FIELD_NUMBER: builtins.int
    MAPPING_TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def index_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def index_pattern(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def mapping_data(self) -> google.protobuf.struct_pb2.Struct: ...
    @property
    def mapping_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        index_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        index_pattern: google.protobuf.wrappers_pb2.StringValue | None = ...,
        mapping_data: google.protobuf.struct_pb2.Struct | None = ...,
        mapping_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["description", b"description", "index_name", b"index_name", "index_pattern", b"index_pattern", "mapping_data", b"mapping_data", "mapping_type", b"mapping_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "index_name", b"index_name", "index_pattern", b"index_pattern", "mapping_data", b"mapping_data", "mapping_type", b"mapping_type"]) -> None: ...

global___CoralogixIndexMappingAssetModel = CoralogixIndexMappingAssetModel

@typing_extensions.final
class CoralogixIndexMappingAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class CoralogixIndexMappingOptions(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INDEX_NAME_FIELD_NUMBER: builtins.int
        INDEX_PATTERN_FIELD_NUMBER: builtins.int
        @property
        def index_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def index_pattern(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            index_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            index_pattern: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["index_name", b"index_name", "index_pattern", b"index_pattern"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["index_name", b"index_name", "index_pattern", b"index_pattern"]) -> None: ...

    INDEX_MAPPINGS_FIELD_NUMBER: builtins.int
    @property
    def index_mappings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CoralogixIndexMappingAssetOptions.CoralogixIndexMappingOptions]: ...
    def __init__(
        self,
        *,
        index_mappings: collections.abc.Iterable[global___CoralogixIndexMappingAssetOptions.CoralogixIndexMappingOptions] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["index_mappings", b"index_mappings"]) -> None: ...

global___CoralogixIndexMappingAssetOptions = CoralogixIndexMappingAssetOptions

@typing_extensions.final
class CoralogixApmServiceAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    WORKLOADS_FIELD_NUMBER: builtins.int
    TECHNOLOGY_FIELD_NUMBER: builtins.int
    SLO_STATUS_COUNT_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def workloads(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def technology(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def slo_status_count(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        type: google.protobuf.wrappers_pb2.StringValue | None = ...,
        workloads: collections.abc.Iterable[builtins.str] | None = ...,
        technology: google.protobuf.wrappers_pb2.StringValue | None = ...,
        slo_status_count: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "slo_status_count", b"slo_status_count", "technology", b"technology", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "slo_status_count", b"slo_status_count", "technology", b"technology", "type", b"type", "workloads", b"workloads"]) -> None: ...

global___CoralogixApmServiceAssetModel = CoralogixApmServiceAssetModel

@typing_extensions.final
class CoralogixApmServiceAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class CoralogixApmServiceOptions(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            type: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name", "type", b"type"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "type", b"type"]) -> None: ...

    SERVICES_FIELD_NUMBER: builtins.int
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CoralogixApmServiceAssetOptions.CoralogixApmServiceOptions]: ...
    def __init__(
        self,
        *,
        services: collections.abc.Iterable[global___CoralogixApmServiceAssetOptions.CoralogixApmServiceOptions] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["services", b"services"]) -> None: ...

global___CoralogixApmServiceAssetOptions = CoralogixApmServiceAssetOptions

@typing_extensions.final
class CoralogixAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CoralogixAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___CoralogixAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___CoralogixAssets = CoralogixAssets
