# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/protos/assets/eks_asset.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from core.protos import base_pb2 as core_dot_protos_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"core/protos/assets/eks_asset.proto\x12\x16\x63ore.protos.connectors\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16\x63ore/protos/base.proto\"h\n\x07\x43ommand\x12*\n\x04type\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0b\x64\x65scription\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"E\n\tNamespace\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0c\n\x04pods\x18\x02 \x03(\t\"l\n\x07\x43luster\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\nnamespaces\x18\x02 \x03(\x0b\x32!.core.protos.connectors.Namespace\"p\n\rRegionCluster\x12,\n\x06region\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x08\x63lusters\x18\x02 \x03(\x0b\x32\x1f.core.protos.connectors.Cluster\"\xaa\x01\n\x14\x45ksClusterAssetModel\x12,\n\x06region\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x08\x63lusters\x18\x02 \x03(\x0b\x32\x1f.core.protos.connectors.Cluster\x12\x31\n\x08\x63ommands\x18\x03 \x03(\x0b\x32\x1f.core.protos.connectors.Command\"P\n\x16\x45ksClusterAssetOptions\x12\x36\n\x07regions\x18\x01 \x03(\x0b\x32%.core.protos.connectors.RegionCluster\"\xf6\x01\n\rEksAssetModel\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12+\n\x0e\x63onnector_type\x18\x02 \x01(\x0e\x32\x13.core.protos.Source\x12*\n\x04type\x18\x03 \x01(\x0e\x32\x1c.core.protos.SourceModelType\x12\x14\n\x0clast_updated\x18\x04 \x01(\x10\x12\x43\n\x0b\x65ks_cluster\x18\x05 \x01(\x0b\x32,.core.protos.connectors.EksClusterAssetModelH\x00\x42\x07\n\x05\x61sset\"B\n\tEksAssets\x12\x35\n\x06\x61ssets\x18\x01 \x03(\x0b\x32%.core.protos.connectors.EksAssetModelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.assets.eks_asset_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMAND']._serialized_start=118
  _globals['_COMMAND']._serialized_end=222
  _globals['_NAMESPACE']._serialized_start=224
  _globals['_NAMESPACE']._serialized_end=293
  _globals['_CLUSTER']._serialized_start=295
  _globals['_CLUSTER']._serialized_end=403
  _globals['_REGIONCLUSTER']._serialized_start=405
  _globals['_REGIONCLUSTER']._serialized_end=517
  _globals['_EKSCLUSTERASSETMODEL']._serialized_start=520
  _globals['_EKSCLUSTERASSETMODEL']._serialized_end=690
  _globals['_EKSCLUSTERASSETOPTIONS']._serialized_start=692
  _globals['_EKSCLUSTERASSETOPTIONS']._serialized_end=772
  _globals['_EKSASSETMODEL']._serialized_start=775
  _globals['_EKSASSETMODEL']._serialized_end=1021
  _globals['_EKSASSETS']._serialized_start=1023
  _globals['_EKSASSETS']._serialized_end=1089
# @@protoc_insertion_point(module_scope)
