# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/protos/assets/mongodb_asset.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from core.protos import base_pb2 as core_dot_protos_dot_base__pb2
from core.protos.connectors import connector_pb2 as core_dot_protos_dot_connectors_dot_connector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&core/protos/assets/mongodb_asset.proto\x12\x16\x63ore.protos.connectors\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16\x63ore/protos/base.proto\x1a&core/protos/connectors/connector.proto\"0\n\x1bMongoDBDatabaseAssetOptions\x12\x11\n\tdatabases\x18\x01 \x03(\t\"4\n\x1dMongoDBCollectionAssetOptions\x12\x13\n\x0b\x63ollections\x18\x01 \x03(\t\"\\\n\x19MongoDBDatabaseAssetModel\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x13\n\x0b\x63ollections\x18\x02 \x03(\t\"y\n\x1bMongoDBCollectionAssetModel\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08\x64\x61tabase\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"\xd7\x02\n\x11MongoDBAssetModel\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12+\n\x0e\x63onnector_type\x18\x02 \x01(\x0e\x32\x13.core.protos.Source\x12*\n\x04type\x18\x03 \x01(\x0e\x32\x1c.core.protos.SourceModelType\x12\x14\n\x0clast_updated\x18\x04 \x01(\x10\x12M\n\x10mongodb_database\x18\x65 \x01(\x0b\x32\x31.core.protos.connectors.MongoDBDatabaseAssetModelH\x00\x12Q\n\x12mongodb_collection\x18\x66 \x01(\x0b\x32\x33.core.protos.connectors.MongoDBCollectionAssetModelH\x00\x42\x07\n\x05\x61sset\"J\n\rMongoDBAssets\x12\x39\n\x06\x61ssets\x18\x01 \x03(\x0b\x32).core.protos.connectors.MongoDBAssetModelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.assets.mongodb_asset_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MONGODBDATABASEASSETOPTIONS']._serialized_start=162
  _globals['_MONGODBDATABASEASSETOPTIONS']._serialized_end=210
  _globals['_MONGODBCOLLECTIONASSETOPTIONS']._serialized_start=212
  _globals['_MONGODBCOLLECTIONASSETOPTIONS']._serialized_end=264
  _globals['_MONGODBDATABASEASSETMODEL']._serialized_start=266
  _globals['_MONGODBDATABASEASSETMODEL']._serialized_end=358
  _globals['_MONGODBCOLLECTIONASSETMODEL']._serialized_start=360
  _globals['_MONGODBCOLLECTIONASSETMODEL']._serialized_end=481
  _globals['_MONGODBASSETMODEL']._serialized_start=484
  _globals['_MONGODBASSETMODEL']._serialized_end=827
  _globals['_MONGODBASSETS']._serialized_start=829
  _globals['_MONGODBASSETS']._serialized_end=903
# @@protoc_insertion_point(module_scope)
