"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.base_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MongoDBDatabaseAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATABASES_FIELD_NUMBER: builtins.int
    @property
    def databases(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Names of databases"""

    def __init__(
        self,
        *,
        databases: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["databases", b"databases"]) -> None: ...

Global___MongoDBDatabaseAssetOptions: typing_extensions.TypeAlias = MongoDBDatabaseAssetOptions

@typing.final
class MongoDBCollectionAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTIONS_FIELD_NUMBER: builtins.int
    @property
    def collections(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Names of collections"""

    def __init__(
        self,
        *,
        collections: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collections", b"collections"]) -> None: ...

Global___MongoDBCollectionAssetOptions: typing_extensions.TypeAlias = MongoDBCollectionAssetOptions

@typing.final
class MongoDBDatabaseAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    COLLECTIONS_FIELD_NUMBER: builtins.int
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def collections(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of collections in this database"""

    def __init__(
        self,
        *,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        collections: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["collections", b"collections", "name", b"name"]) -> None: ...

Global___MongoDBDatabaseAssetModel: typing_extensions.TypeAlias = MongoDBDatabaseAssetModel

@typing.final
class MongoDBCollectionAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATABASE_FIELD_NUMBER: builtins.int
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def database(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        database: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["database", b"database", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["database", b"database", "name", b"name"]) -> None: ...

Global___MongoDBCollectionAssetModel: typing_extensions.TypeAlias = MongoDBCollectionAssetModel

@typing.final
class MongoDBAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    MONGODB_DATABASE_FIELD_NUMBER: builtins.int
    MONGODB_COLLECTION_FIELD_NUMBER: builtins.int
    connector_type: core.protos.base_pb2.Source.ValueType
    type: core.protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def mongodb_database(self) -> Global___MongoDBDatabaseAssetModel: ...
    @property
    def mongodb_collection(self) -> Global___MongoDBCollectionAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: core.protos.base_pb2.Source.ValueType = ...,
        type: core.protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        mongodb_database: Global___MongoDBDatabaseAssetModel | None = ...,
        mongodb_collection: Global___MongoDBCollectionAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["asset", b"asset", "id", b"id", "mongodb_collection", b"mongodb_collection", "mongodb_database", b"mongodb_database"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["asset", b"asset", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "mongodb_collection", b"mongodb_collection", "mongodb_database", b"mongodb_database", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["asset", b"asset"]) -> typing.Literal["mongodb_database", "mongodb_collection"] | None: ...

Global___MongoDBAssetModel: typing_extensions.TypeAlias = MongoDBAssetModel

@typing.final
class MongoDBAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___MongoDBAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[Global___MongoDBAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["assets", b"assets"]) -> None: ...

Global___MongoDBAssets: typing_extensions.TypeAlias = MongoDBAssets
