"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.base_pb2
import core.protos.connectors.api_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SlackChannelAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ChannelMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        WORKSPACE_ID_FIELD_NUMBER: builtins.int
        WORKSPACE_NAME_FIELD_NUMBER: builtins.int
        INVITER_ID_FIELD_NUMBER: builtins.int
        IS_DM_FIELD_NUMBER: builtins.int
        @property
        def workspace_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def workspace_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def inviter_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def is_dm(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            workspace_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            workspace_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            inviter_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            is_dm: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["inviter_id", b"inviter_id", "is_dm", b"is_dm", "workspace_id", b"workspace_id", "workspace_name", b"workspace_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["inviter_id", b"inviter_id", "is_dm", b"is_dm", "workspace_id", b"workspace_id", "workspace_name", b"workspace_name"]) -> None: ...

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    CHANNEL_NAME_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    ALERT_OPS_CONFIGURATION_FIELD_NUMBER: builtins.int
    @property
    def channel_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def channel_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def metadata(self) -> global___SlackChannelAssetModel.ChannelMetadata: ...
    @property
    def alert_ops_configuration(self) -> core.protos.connectors.api_pb2.SlackAlertOpsConfiguration: ...
    def __init__(
        self,
        *,
        channel_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        channel_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        metadata: global___SlackChannelAssetModel.ChannelMetadata | None = ...,
        alert_ops_configuration: core.protos.connectors.api_pb2.SlackAlertOpsConfiguration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["alert_ops_configuration", b"alert_ops_configuration", "channel_id", b"channel_id", "channel_name", b"channel_name", "metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["alert_ops_configuration", b"alert_ops_configuration", "channel_id", b"channel_id", "channel_name", b"channel_name", "metadata", b"metadata"]) -> None: ...

global___SlackChannelAssetModel = SlackChannelAssetModel

@typing.final
class SlackChannelAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_IDS_FIELD_NUMBER: builtins.int
    @property
    def channel_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        channel_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_ids", b"channel_ids"]) -> None: ...

global___SlackChannelAssetOptions = SlackChannelAssetOptions

@typing.final
class SlackAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    SLACK_CHANNEL_FIELD_NUMBER: builtins.int
    connector_type: core.protos.base_pb2.Source.ValueType
    type: core.protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def slack_channel(self) -> global___SlackChannelAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: core.protos.base_pb2.Source.ValueType = ...,
        type: core.protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        slack_channel: global___SlackChannelAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["asset", b"asset", "id", b"id", "slack_channel", b"slack_channel"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["asset", b"asset", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "slack_channel", b"slack_channel", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["asset", b"asset"]) -> typing.Literal["slack_channel"] | None: ...

global___SlackAssetModel = SlackAssetModel

@typing.final
class SlackAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SlackAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___SlackAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["assets", b"assets"]) -> None: ...

global___SlackAssets = SlackAssets
