# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/protos/assets/victoria_logs_asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from core.protos import base_pb2 as core_dot_protos_dot_base__pb2
from core.protos.connectors import connector_pb2 as core_dot_protos_dot_connectors_dot_connector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,core/protos/assets/victoria_logs_asset.proto\x12\x16\x63ore.protos.connectors\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16\x63ore/protos/base.proto\x1a&core/protos/connectors/connector.proto\"/\n\x1dVictoriaLogsFieldAssetOptions\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\"(\n\x16VictoriaLogsFieldModel\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\"\x89\x02\n\x16VictoriaLogsAssetModel\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12+\n\x0e\x63onnector_type\x18\x02 \x01(\x0e\x32\x13.core.protos.Source\x12*\n\x04type\x18\x03 \x01(\x0e\x32\x1c.core.protos.SourceModelType\x12\x14\n\x0clast_updated\x18\x04 \x01(\x03\x12M\n\x13victoria_logs_field\x18\x05 \x01(\x0b\x32..core.protos.connectors.VictoriaLogsFieldModelH\x00\x42\x07\n\x05\x61sset\"T\n\x12VictoriaLogsAssets\x12>\n\x06\x61ssets\x18\x01 \x03(\x0b\x32..core.protos.connectors.VictoriaLogsAssetModelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.assets.victoria_logs_asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VICTORIALOGSFIELDASSETOPTIONS._serialized_start=168
  _VICTORIALOGSFIELDASSETOPTIONS._serialized_end=215
  _VICTORIALOGSFIELDMODEL._serialized_start=217
  _VICTORIALOGSFIELDMODEL._serialized_end=257
  _VICTORIALOGSASSETMODEL._serialized_start=260
  _VICTORIALOGSASSETMODEL._serialized_end=525
  _VICTORIALOGSASSETS._serialized_start=527
  _VICTORIALOGSASSETS._serialized_end=611
# @@protoc_insertion_point(module_scope)
