"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.auto_investigation_rule.auto_investigation_rule_pb2
import core.protos.connectors.api_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetAutoInvestigationRuleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    AUTO_INVESTIGATION_RULE_IDS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def auto_investigation_rule_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        auto_investigation_rule_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["auto_investigation_rule_ids", b"auto_investigation_rule_ids", "meta", b"meta"]) -> None: ...

global___GetAutoInvestigationRuleRequest = GetAutoInvestigationRuleRequest

@typing.final
class GetAutoInvestigationRuleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    AUTO_INVESTIGATION_RULES_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> core.protos.connectors.api_pb2.Meta: ...
    @property
    def auto_investigation_rules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.auto_investigation_rule.auto_investigation_rule_pb2.AutoInvestigationRule]: ...
    def __init__(
        self,
        *,
        meta: core.protos.connectors.api_pb2.Meta | None = ...,
        auto_investigation_rules: collections.abc.Iterable[core.protos.auto_investigation_rule.auto_investigation_rule_pb2.AutoInvestigationRule] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["auto_investigation_rules", b"auto_investigation_rules", "meta", b"meta"]) -> None: ...

global___GetAutoInvestigationRuleResponse = GetAutoInvestigationRuleResponse

@typing.final
class CreateAutoInvestigationRuleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    AUTO_INVESTIGATION_RULE_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def auto_investigation_rule(self) -> core.protos.auto_investigation_rule.auto_investigation_rule_pb2.AutoInvestigationRule: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        auto_investigation_rule: core.protos.auto_investigation_rule.auto_investigation_rule_pb2.AutoInvestigationRule | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["auto_investigation_rule", b"auto_investigation_rule"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["auto_investigation_rule", b"auto_investigation_rule", "name", b"name"]) -> None: ...

global___CreateAutoInvestigationRuleRequest = CreateAutoInvestigationRuleRequest

@typing.final
class CreateAutoInvestigationRuleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    AUTO_INVESTIGATION_RULE_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    @property
    def auto_investigation_rule(self) -> core.protos.auto_investigation_rule.auto_investigation_rule_pb2.AutoInvestigationRule: ...
    def __init__(
        self,
        *,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
        auto_investigation_rule: core.protos.auto_investigation_rule.auto_investigation_rule_pb2.AutoInvestigationRule | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["auto_investigation_rule", b"auto_investigation_rule", "message", b"message", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["auto_investigation_rule", b"auto_investigation_rule", "message", b"message", "success", b"success"]) -> None: ...

global___CreateAutoInvestigationRuleResponse = CreateAutoInvestigationRuleResponse

@typing.final
class UpdateAutoInvestigationRuleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTO_INVESTIGATION_RULE_ID_FIELD_NUMBER: builtins.int
    UPDATE_AUTO_INVESTIGATION_RULE_OPS_FIELD_NUMBER: builtins.int
    @property
    def auto_investigation_rule_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def update_auto_investigation_rule_ops(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.protos.auto_investigation_rule.auto_investigation_rule_pb2.UpdateAutoInvestigationRuleOp]: ...
    def __init__(
        self,
        *,
        auto_investigation_rule_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        update_auto_investigation_rule_ops: collections.abc.Iterable[core.protos.auto_investigation_rule.auto_investigation_rule_pb2.UpdateAutoInvestigationRuleOp] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["auto_investigation_rule_id", b"auto_investigation_rule_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["auto_investigation_rule_id", b"auto_investigation_rule_id", "update_auto_investigation_rule_ops", b"update_auto_investigation_rule_ops"]) -> None: ...

global___UpdateAutoInvestigationRuleRequest = UpdateAutoInvestigationRuleRequest

@typing.final
class UpdateAutoInvestigationRuleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> core.protos.connectors.api_pb2.Message: ...
    def __init__(
        self,
        *,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: core.protos.connectors.api_pb2.Message | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___UpdateAutoInvestigationRuleResponse = UpdateAutoInvestigationRuleResponse
