"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import core.protos.alert_ops_pb2
import core.protos.auto_investigation_rule.rules.cron_schedule_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AutoInvestigationRule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RuleType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RuleTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AutoInvestigationRule._RuleType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: AutoInvestigationRule._RuleType.ValueType  # 0
        CRON_RULE: AutoInvestigationRule._RuleType.ValueType  # 1

    class RuleType(_RuleType, metaclass=_RuleTypeEnumTypeWrapper): ...
    UNKNOWN: AutoInvestigationRule.RuleType.ValueType  # 0
    CRON_RULE: AutoInvestigationRule.RuleType.ValueType  # 1

    RULE_TYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    USER_INPUT_PROMPT_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    LAST_SCHEDULED_AT_FIELD_NUMBER: builtins.int
    NOTIFICATION_METADATA_FIELD_NUMBER: builtins.int
    SUMMARY_METADATA_FIELD_NUMBER: builtins.int
    PLAYBOOK_IDS_FIELD_NUMBER: builtins.int
    CRON_RULE_FIELD_NUMBER: builtins.int
    rule_type: global___AutoInvestigationRule.RuleType.ValueType
    last_scheduled_at: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def user_input_prompt(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def created_at(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def created_by(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def notification_metadata(self) -> core.protos.alert_ops_pb2.ScheduleNotificationMetadata: ...
    @property
    def summary_metadata(self) -> core.protos.alert_ops_pb2.ScheduleSummaryMetadata: ...
    @property
    def playbook_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.wrappers_pb2.UInt64Value]: ...
    @property
    def cron_rule(self) -> core.protos.auto_investigation_rule.rules.cron_schedule_pb2.AutoInvestigationCronScheduleRule: ...
    def __init__(
        self,
        *,
        rule_type: global___AutoInvestigationRule.RuleType.ValueType = ...,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        user_input_prompt: google.protobuf.wrappers_pb2.StringValue | None = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        created_at: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        created_by: google.protobuf.wrappers_pb2.StringValue | None = ...,
        last_scheduled_at: builtins.int = ...,
        notification_metadata: core.protos.alert_ops_pb2.ScheduleNotificationMetadata | None = ...,
        summary_metadata: core.protos.alert_ops_pb2.ScheduleSummaryMetadata | None = ...,
        playbook_ids: collections.abc.Iterable[google.protobuf.wrappers_pb2.UInt64Value] | None = ...,
        cron_rule: core.protos.auto_investigation_rule.rules.cron_schedule_pb2.AutoInvestigationCronScheduleRule | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at", "created_by", b"created_by", "cron_rule", b"cron_rule", "id", b"id", "is_active", b"is_active", "name", b"name", "notification_metadata", b"notification_metadata", "rule", b"rule", "summary_metadata", b"summary_metadata", "user_input_prompt", b"user_input_prompt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "created_by", b"created_by", "cron_rule", b"cron_rule", "id", b"id", "is_active", b"is_active", "last_scheduled_at", b"last_scheduled_at", "name", b"name", "notification_metadata", b"notification_metadata", "playbook_ids", b"playbook_ids", "rule", b"rule", "rule_type", b"rule_type", "summary_metadata", b"summary_metadata", "user_input_prompt", b"user_input_prompt"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["rule", b"rule"]) -> typing.Literal["cron_rule"] | None: ...

global___AutoInvestigationRule = AutoInvestigationRule

@typing.final
class UpdateAutoInvestigationRuleOp(google.protobuf.message.Message):
    """/////////////////// Auto Investigation Rule Update Ops Proto /////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Op:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OpEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdateAutoInvestigationRuleOp._Op.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: UpdateAutoInvestigationRuleOp._Op.ValueType  # 0
        UPDATE_AUTO_INVESTIGATION_RULE_NAME: UpdateAutoInvestigationRuleOp._Op.ValueType  # 1
        UPDATE_AUTO_INVESTIGATION_RULE_STATUS: UpdateAutoInvestigationRuleOp._Op.ValueType  # 2
        UPDATE_AUTO_INVESTIGATION_RULE: UpdateAutoInvestigationRuleOp._Op.ValueType  # 3
        UPDATE_NOTIFICATION_METADATA: UpdateAutoInvestigationRuleOp._Op.ValueType  # 4
        UPDATE_SUMMARY_METADATA: UpdateAutoInvestigationRuleOp._Op.ValueType  # 5

    class Op(_Op, metaclass=_OpEnumTypeWrapper): ...
    UNKNOWN: UpdateAutoInvestigationRuleOp.Op.ValueType  # 0
    UPDATE_AUTO_INVESTIGATION_RULE_NAME: UpdateAutoInvestigationRuleOp.Op.ValueType  # 1
    UPDATE_AUTO_INVESTIGATION_RULE_STATUS: UpdateAutoInvestigationRuleOp.Op.ValueType  # 2
    UPDATE_AUTO_INVESTIGATION_RULE: UpdateAutoInvestigationRuleOp.Op.ValueType  # 3
    UPDATE_NOTIFICATION_METADATA: UpdateAutoInvestigationRuleOp.Op.ValueType  # 4
    UPDATE_SUMMARY_METADATA: UpdateAutoInvestigationRuleOp.Op.ValueType  # 5

    @typing.final
    class UpdateAutoInvestigationRuleName(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["name", b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

    @typing.final
    class UpdateAutoInvestigationRuleStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_ACTIVE_FIELD_NUMBER: builtins.int
        @property
        def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["is_active", b"is_active"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["is_active", b"is_active"]) -> None: ...

    @typing.final
    class UpdateAutoInvestigationRule(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AUTO_INVESTIGATION_RULE_FIELD_NUMBER: builtins.int
        @property
        def auto_investigation_rule(self) -> global___AutoInvestigationRule: ...
        def __init__(
            self,
            *,
            auto_investigation_rule: global___AutoInvestigationRule | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["auto_investigation_rule", b"auto_investigation_rule"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["auto_investigation_rule", b"auto_investigation_rule"]) -> None: ...

    @typing.final
    class UpdateNotificationMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NOTIFICATION_METADATA_FIELD_NUMBER: builtins.int
        @property
        def notification_metadata(self) -> core.protos.alert_ops_pb2.ScheduleNotificationMetadata: ...
        def __init__(
            self,
            *,
            notification_metadata: core.protos.alert_ops_pb2.ScheduleNotificationMetadata | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["notification_metadata", b"notification_metadata"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["notification_metadata", b"notification_metadata"]) -> None: ...

    @typing.final
    class UpdateSummaryMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SUMMARY_METADATA_FIELD_NUMBER: builtins.int
        @property
        def summary_metadata(self) -> core.protos.alert_ops_pb2.ScheduleSummaryMetadata: ...
        def __init__(
            self,
            *,
            summary_metadata: core.protos.alert_ops_pb2.ScheduleSummaryMetadata | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["summary_metadata", b"summary_metadata"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["summary_metadata", b"summary_metadata"]) -> None: ...

    OP_FIELD_NUMBER: builtins.int
    UPDATE_AUTO_INVESTIGATION_RULE_NAME_FIELD_NUMBER: builtins.int
    UPDATE_AUTO_INVESTIGATION_RULE_STATUS_FIELD_NUMBER: builtins.int
    UPDATE_AUTO_INVESTIGATION_RULE_FIELD_NUMBER: builtins.int
    UPDATE_NOTIFICATION_METADATA_FIELD_NUMBER: builtins.int
    UPDATE_SUMMARY_METADATA_FIELD_NUMBER: builtins.int
    op: global___UpdateAutoInvestigationRuleOp.Op.ValueType
    @property
    def update_auto_investigation_rule_name(self) -> global___UpdateAutoInvestigationRuleOp.UpdateAutoInvestigationRuleName: ...
    @property
    def update_auto_investigation_rule_status(self) -> global___UpdateAutoInvestigationRuleOp.UpdateAutoInvestigationRuleStatus: ...
    @property
    def update_auto_investigation_rule(self) -> global___UpdateAutoInvestigationRuleOp.UpdateAutoInvestigationRule: ...
    @property
    def update_notification_metadata(self) -> global___UpdateAutoInvestigationRuleOp.UpdateNotificationMetadata: ...
    @property
    def update_summary_metadata(self) -> global___UpdateAutoInvestigationRuleOp.UpdateSummaryMetadata: ...
    def __init__(
        self,
        *,
        op: global___UpdateAutoInvestigationRuleOp.Op.ValueType = ...,
        update_auto_investigation_rule_name: global___UpdateAutoInvestigationRuleOp.UpdateAutoInvestigationRuleName | None = ...,
        update_auto_investigation_rule_status: global___UpdateAutoInvestigationRuleOp.UpdateAutoInvestigationRuleStatus | None = ...,
        update_auto_investigation_rule: global___UpdateAutoInvestigationRuleOp.UpdateAutoInvestigationRule | None = ...,
        update_notification_metadata: global___UpdateAutoInvestigationRuleOp.UpdateNotificationMetadata | None = ...,
        update_summary_metadata: global___UpdateAutoInvestigationRuleOp.UpdateSummaryMetadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["update", b"update", "update_auto_investigation_rule", b"update_auto_investigation_rule", "update_auto_investigation_rule_name", b"update_auto_investigation_rule_name", "update_auto_investigation_rule_status", b"update_auto_investigation_rule_status", "update_notification_metadata", b"update_notification_metadata", "update_summary_metadata", b"update_summary_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["op", b"op", "update", b"update", "update_auto_investigation_rule", b"update_auto_investigation_rule", "update_auto_investigation_rule_name", b"update_auto_investigation_rule_name", "update_auto_investigation_rule_status", b"update_auto_investigation_rule_status", "update_notification_metadata", b"update_notification_metadata", "update_summary_metadata", b"update_summary_metadata"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["update", b"update"]) -> typing.Literal["update_auto_investigation_rule_name", "update_auto_investigation_rule_status", "update_auto_investigation_rule", "update_notification_metadata", "update_summary_metadata"] | None: ...

global___UpdateAutoInvestigationRuleOp = UpdateAutoInvestigationRuleOp
