# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/protos/playbooks/playbook_templates/api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from core.protos.connectors import api_pb2 as core_dot_protos_dot_connectors_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2core/protos/playbooks/playbook_templates/api.proto\x12(core.protos.playbooks.playbook_templates\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a core/protos/connectors/api.proto\"}\n!ImportPlaybookTemplatesGetRequest\x12*\n\x04meta\x18\x01 \x01(\x0b\x32\x1c.core.protos.connectors.Meta\x12,\n\x0bimport_sops\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xaa\x01\n\"ImportPlaybookTemplatesGetResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x07message\x18\x02 \x01(\x0b\x32\x1f.core.protos.connectors.Message\x12%\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x17.google.protobuf.Structb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.protos.playbooks.playbook_templates.api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMPORTPLAYBOOKTEMPLATESGETREQUEST._serialized_start=192
  _IMPORTPLAYBOOKTEMPLATESGETREQUEST._serialized_end=317
  _IMPORTPLAYBOOKTEMPLATESGETRESPONSE._serialized_start=320
  _IMPORTPLAYBOOKTEMPLATESGETRESPONSE._serialized_end=490
# @@protoc_insertion_point(module_scope)
