# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/connectors/api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos.connectors import connector_pb2 as protos_dot_connectors_dot_connector__pb2
from protos import base_pb2 as protos_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/connectors/api.proto\x12\x16\x63ore.protos.connectors\x1a\x1egoogle/protobuf/wrappers.proto\x1a!protos/connectors/connector.proto\x1a\x11protos/base.proto\"L\n\x14TestConnectorRequest\x12\x34\n\tconnector\x18\x01 \x01(\x0b\x32!.core.protos.connectors.Connector\"k\n\x15TestConnectorResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12%\n\x07message\x18\x02 \x01(\x0b\x32\x14.core.protos.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.connectors.api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTCONNECTORREQUEST']._serialized_start=141
  _globals['_TESTCONNECTORREQUEST']._serialized_end=217
  _globals['_TESTCONNECTORRESPONSE']._serialized_start=219
  _globals['_TESTCONNECTORRESPONSE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
